<template>
  <Sidebar
    position="right"
    v-if="showDialog"
    v-model:visible="showDialog"
    modal
    :show-close-icon="false"
    #container
  >
    <div class="overflow-y-scroll">
      <MobileToolbar class="bg-gray-800 text-white">
        <template #start>
          <slot name="headerLeft"></slot>
        </template>
        <template #center>
          <slot name="headerCenter"></slot>
        </template>
        <template #end>
          <slot name="headerRight"></slot>
        </template>
      </MobileToolbar>
      <div >
        <slot name="default"></slot>
      </div>
    </div>
  </Sidebar>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
const showDialog = defineModel<boolean>({ required: true });
const props = defineProps<{ closeEventName: string }>();
useNuxtApp().$listen("CloseDialog", (closeEventName: string) => {
  if (props.closeEventName == closeEventName) {
    showDialog.value = false;
  }
});
</script>
