<template>
  <Sidebar
    position="bottom"
    v-if="showDialog"
    v-model:visible="showDialog"
    modal
    :show-close-icon="false"
    #container
  >
    <div class="overflow-y-scroll">
      <slot name="default"></slot>
    </div>
  </Sidebar>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
const showDialog = defineModel<boolean>({ required: true });
useNuxtApp().$listen("CloseDialog", (closeEventName: string) => {
  if (closeEventName == "viewer") showDialog.value = false;
});
</script>
