<template>
    <Dialog modal v-model:visible="visible" :closable="false" 
        :pt="{
            root:{class:'w-auto'},            
            }">
        <div class=" items-center justify-center flex flex-col ">
            <ProgressSpinner />
        </div>
        
    </Dialog>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2024-03-13
 * Author: Ks Tan
 */
const visible = ref(false)
onMounted(()=>{

    useNuxtApp().$listen('HoldScreen',(ishold)=>{
        visible.value=ishold
    })
})
</script>