<template>

  <Dialog  v-model:visible="showDialog" modal :pt="{root:{class:'w-1/3'}}"
    :header="t('sessionExpire')">          
        <div>
          {{ t('reloginMessage') }}
        </div>
        <div class="text-right">
          <Button @click="relogin" class="btn-primary">
            {{ t('login') }}
          </Button>
        </div>
        
      
      </Dialog>
  
  
    
      
  </template>
  <script lang="ts" setup>
  /**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
  import {PROFILEApi} from '~/simpleapp/generate/openapi'
  const showDialog = ref(false)
  const tabvisible = ref('')
  
  
  addEventListener("visibilitychange", async (event) => {
    tabvisible.value = document.visibilityState  
    
    if(document.visibilityState  ==='visible'){
      //focus tab, try session still active?    
      const result = await getApiSession()    
      if(result){
        showDialog.value=false
      }else{
        showDialog.value=true
      }
    }
  });
  
  
  const relogin= ()=>{
      window.open(useRuntimeConfig().public.APP_URL+'/relogin')
  }
  
  
  
  
  </script>