<template>
  <div class="flex flex-row h-full">
    <div>
      <SidebarSideBarContainer> reportlist </SidebarSideBarContainer>
    </div>
    <div>
      <div>reports body</div>
    </div>
  </div>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator. It is changable
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-23
 * Author: Ks Tan
 */
</script>