<template>
    <div class="h-full flex flex-row">
        <div class="flex flex-col h-screen ">        
            <div class="flex-1">            
                <div class="" v-for="item in menus">
                        <div class="">                    
                            <NuxtLink   v-if="item.path !==undefined"
                                :class="`pi ${item.iconClass} p-2  text-6xl cursor-pointer`"
                                :to="getDocumentUrl(item.path)"
                                ></NuxtLink>
                            <div v-else-if="item.command" :class="`pi ${item.iconClass} p-2  text-6xl cursor-pointer`" @click="item.command">
                        </div>
                    </div> 
                </div>
            </div>                    
            <div class="p-2 text-6xl cursor-pointer pi pi-user dark:text-white" @click="openProfile">
                <HeaderButtonProfile v-model="showProfile"/>           
            </div>
            
        </div>        
        <div class="flex-1">
            <HeaderBar />
            <UserInvitation/>
            <slot></slot>
        </div>                
    </div>
    <div >
        <HeaderButtonMenuPicker v-model="showMenu"></HeaderButtonMenuPicker>
    </div>
    
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
const showMenu =ref(false)
const showProfile =ref(false)

const openMenu = ()=>showMenu.value=true
const openProfile = ()=>showProfile.value=true

const menus=[    
    {iconClass:'pi-home dark:text-white',path:''},
    //{iconClass:'pi-users dark:text-white',path:'managestudents/new'},
    //{iconClass:'pi-calendar dark:text-white',path:`manageclasses`},
    // {iconClass:'pi-database',path:'managedata'},
    {iconClass:'pi-chart-pie dark:text-white',path:'reports'},
    {iconClass:'pi-bars dark:text-white',command: openMenu},    
 

]
</script>