<template>
        <slot v-if="useRoute().path=='/login'"></slot>        
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
</script>