<template>
    <div class="h-screen flex flex-col ">
        
        <div class="flex flex-col grow overflow-y-auto">
            <div class="flex flex-col mb-14 w-full">
                <ListMessages v-model="messagesVisible"/>
                <UserInvitation/>
                <slot></slot>                          
            </div>                                      
        </div> 
        <!-- fixed -->
        <div v-if="getCurrentXorg()" class="flex h-16  border-t-2 dark:border-t-gray-700  text-3xl  flex-row   left-0 w-full  justify justify-between bottom-0 fixed z-50 bg-white dark:bg-slate-900 opacity opacity-95 " > 
                <div v-if="getUserProfile()?.currentGroup=='teacher'" class="flex flex-row">
                    <NuxtLink  :class="`pi pi-home p-4 cursor-pointer inline-block align-middle`" :to="getDocumentUrl('')" />
                    <ButtonText  class="cursor-pointer inline-block align-middle" @click="openMessages">
                        <i class="pi pi-envelope p-1" ></i>
                        <Badge v-if="systemMsgQty" class="-ml-4" :value="systemMsgQty"></Badge>
                    </ButtonText>
                    <ButtonText  :class="`pi pi-user p-4 cursor-pointer inline-block align-middle`" @click="openProfile"/>
                </div>
                <div v-else  class="flex flex-row">
                    <NuxtLink  :class="`pi pi-home p-4 cursor-pointer inline-block align-middle`" :to="getDocumentUrl('')" />
                    
                    <ButtonText  :class="`pi pi-bars p-4 cursor-pointer inline-block align-middle`" @click="openMenu"/>
                    <ButtonText  class="cursor-pointer inline-block align-middle" @click="openMessages">
                        <i class="pi pi-envelope p-1" ></i>
                        <Badge v-if="systemMsgQty" class="-ml-4" :value="systemMsgQty"></Badge>
                    </ButtonText>
                    <ButtonText  :class="`pi pi-user p-4 cursor-pointer inline-block align-middle`" @click="openProfile"/>                    
                </div>
                
                <HeaderButtonMenuPicker v-model="showMenu"></HeaderButtonMenuPicker>
                <HeaderButtonProfile v-model="showProfile"/>
                
        </div> 
        
        
        <!-- <HeaderBar class="border flex flex-row h-10 fixed left-0 w-full  justify justify-between top-0 z-50 bg-white  dark:bg-gray-800"/> -->
     
    </div>

</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * last change 2024-04-10
 * author: Ks Tan
 */
const showMenu =ref(false)
const showProfile =ref(false)
const messagesVisible = ref(false)
const openMenu = ()=>showMenu.value=true
const openProfile = ()=>showProfile.value=true
const openMessages=() => messagesVisible.value = true


type MenuType = {iconClass:string,path?:string,command?:Function}



</script>
