<template>
  <div class="text-base text-gray-600 dark:text-gray-500">
    <slot name="default"></slot>
  </div>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
</script>