<template>
  <div class="text-base font font-bold">
    <slot name="default"></slot>
  </div>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-04-24
 * author: Ks Tan
 */
</script>
