<template>
  <LazyFormDocnoformat :_id="_id" @after="after" />
</template>

<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * last change 2023-09-09
 * author: Ks Tan
 */

import { Docnoformat } from "~/simpleapp/generate/types";
const doc = useNuxtApp().$DocnoformatDoc();

const props = defineProps<{ _id: string }>();
const after = (actionName: string, data: Docnoformat) => {
  console.log("Docnoformat capture after emits ", actionName);
  switch (actionName) {
    case "new":
      goTo(doc.getDocName(), "new");
      break;
    case "create":
      goTo(doc.getDocName(), data._id);
      refreshDocumentList(doc.getDocName());
      useNuxtApp().$event("CloseDialog", doc.getDocName().toLowerCase());
      break;
    case "update":
      refreshDocumentList(doc.getDocName());
      useNuxtApp().$event("CloseDialog", doc.getDocName().toLowerCase());
      break;
    case "delete":
      goTo(doc.getDocName(), "new");
      refreshDocumentList(doc.getDocName());
      useNuxtApp().$event("CloseDialog", doc.getDocName().toLowerCase());
      break;
  }
};
</script>
