/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2023-10-28
 * Author: Ks Tan
 */

export const activatePusher =()=>{
  clearChannel()
  subscribeHotValueText(`messages:${getUserProfile()?.uid}`,async (msg:string)=>{
      refreshDocumentList('systemmessage')      
    })
}
