<template>
    <div class="flex flex-col ">
      <label v-if="label" :for="inputid">{{ label }}</label>
      <Calendar 
        v-model="modelValue" 
        class="w-full" 
        :inputid="inputid"
        :date-format="getPrimevueCalendarDateFormat()"
        />
    </div>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization.
 * IT IS NOT CHANGABLE
 * last change 2024-04-16
 * author: Ks Tan
 */
const modelValue = defineModel<Date>({required:true})
const inputid=randomUUID()
const props = defineProps<{
    label?:string
}>()
</script>