<template>
  <VueCal
    :id="id"
    class="w-full"
    hide-view-selector
    click-to-navigate
    :time="false"
    today-button
    active-view="month"
    :disable-views="['week', 'day']"
    :selected-date="selectedDate"
    events-count-on-year-view
    @view-change="viewChange"
    :events="allevents"
    @cell-focus="chooseDate"

    xsmall
  >
    <template #today-button>
      <!-- Using Vuetify (but we prefer Wave UI 🤘) -->
      <div      
       @click="chooseDate(new Date(), true)">{{ t("today") }}</div>
    </template>
    <template #cell-content="{ cell, events }">
      <div>
        <div>
          <s
            v-if="dateExists(new Date(cell.formattedDate), alloffdays)"
            v-tooltip="getHolidayName(new Date(cell.formattedDate))"
            class="text text-red-400 font-bold"
            >{{ cell.content }}</s
          >
          <span v-else>{{ cell.content }} </span>
        </div>
        <div>
          <slot name="default" :cell="cell" :events="events">
            <Badge
              v-if="events.length > 0"
              @contextmenu="(mouseevent) => onRightClickDate(mouseevent, cell)"
              severity="info"
              :value="events.length"
            />
          </slot>
        </div>
      </div>
    </template>
  </VueCal>
</template>
<script lang="ts" setup generic="T">
/**
 * This file was automatically generated by simpleapp generator during initialization.
 * IT IS NOT CHANGABLE
 * last change 2024-02-22
 * author: Ks Tan
 */
//, { Event, SplitDaysAttributes }
import VueCal from "vue-cal";
import "vue-cal/dist/vuecal.css";
import {
  CalEventType,
  CalRightClickEvent,
  OffDay,
  CalViewChange,
} from "~/types";
const viewStatus = ref<CalViewChange>();
const props = defineProps<{
  id: string;
  items: CalEventType<T>[];
  offdays: OffDay[];
}>();
const emits = defineEmits(["chooseDate", "rightClick"]);
const alloffdays = computed(() => props.offdays.map((item) => item.date));
const selectedDate = defineModel<Date>({ required: true });
const getHolidayName = (date: Date) =>
  props.offdays.find((item) => item.date.getTime() == date.getTime())?.title;
const allevents = computed(() => {
  const list = props.items.map((item) => {
    if (item.start instanceof Date)
      item.start = item.start.format("YYYY-MM-DD HH:mm");
    else if (typeof item.start == 'string' ){
      item.start = item.start.substring(0,16).replace('T',' ');
    }
    if (item.end instanceof Date)
      item.end = item.end.format("YYYY-MM-DD HH:mm");
    else if (typeof item.end == 'string' ){
      item.end = item.end.substring(0,16).replace('T',' ');
    }
    return item;
  });
  return list;
});
const viewChange = (event: CalViewChange) => {
  viewStatus.value = event;
};

const chooseDate = (date1: Date, force?: boolean) => {
  if (force || !viewStatus.value || viewStatus.value.view == "month") {
    selectedDate.value = date1;
    emits("chooseDate", date1);
  }
};
const onRightClickDate = (e: MouseEvent, cell: CalRightClickEvent) => {
  emits("rightClick", e, cell);
};
</script>
