<template>
  <VueCal
    :id="id"
    ref="vueresourcecal"
    :disable-views="['years', 'year', 'month', 'week']"
    :time-from="8 * 60"
    :time-to="22 * 60"
    :time-step="30"
    active-view="day"
    :snap-to-time="15"
    hide-view-selector
    :events="allEvents"
    :editable-events="calendarMode"
    :split-days="allresources"
    :min-split-width="100"
    sticky-split-labels
    :selected-date="selectedDate"
    :drag-to-create-threshold="15"
    :on-event-click="onEventClick"
    
    @event-drag-create="onDragNew"
    @event-drop="onEventDrop"
    @view-change="viewChange"
    @cell-click="onCellClick"
    @cell-contextmenu="eventHappend"
  >
    <!-- header template -->
    <template #split-label="{ split }">
      <div
        @click="clickResource(split._id, split.label)"
        class="cursor-pointer"
      >
        <!-- <div
            v-if="resourceType == CalResourceType.teacher && split.email"
            class="w-full text-center"
            >
            <img
                :src="getAvatarLink(split.email, 48)"
                class="overflow-hidden object-cover rounded-full border-2 border-white dark:border-gray-700 shadow"
            /> -->
        <div>
          {{ split.displayName }}
          <span v-if="split._id == '?'" class="pi pi-plus"></span>
        </div>
        <!-- </div>
            <div v-else>{{ split.displayName }}</div> -->
      </div>
    </template>

    <!-- event template -->
    <!--  @contextmenu="onRightClick($event, event)" -->
    <template #event="{ event }">
      <div class="cursor-pointer h-full">
        <slot name="default" :event="<CalEventType<T>>event">
          <div>{{ event.title }}</div>
          <div>{{ event.start }}</div>
          <div>{{ event.end }}</div>
        </slot>
      </div>
    </template>
  </VueCal>
</template>
<script setup lang="ts" generic="T">
/**
 * This file was automatically generated by simpleapp generator during initialization.
 * IT IS NOT CHANGABLE
 * last change 2024-02-22
 * author: Ks Tan
 */


import VueCal, { Event, SplitDaysAttributes } from "vue-cal";
import {
  CalEventType,
  CalViewClickSlotEvent,
  CalResource,
  CalResourceType,
  RelocateEvent,
} from "~/types";
import { emit } from "process";
import moment from "moment";
const timezoneoffset = new Date().getTimezoneOffset();
const eventsdata = ref<CalEventType<T>[]>();
const vueresourcecal = ref();
const emits = defineEmits([
  "eventRightClick",
  "eventClick",
  "eventDrop",
  "eventDragNew",
  "viewChange",
  "resourceClick",
  "slotClick",
]);
const props = defineProps<{
  id: string;
  items: CalEventType<T>[];
  resources: CalResource[];
  resourceType: CalResourceType;
}>();
const selectedDate = defineModel<Date>();
const selectedSchedule = ref<CalEventType<T>>();
const allEvents = ref<CalEventType[]>([]);

const mapEvents = () => {
  allEvents.value = props.items.map((item) => {
    if (item.start instanceof Date)
      item.start = item.start
        .addMinutes(timezoneoffset)
        .format("YYYY-MM-DD HH:mm");
    if (item.end instanceof Date)
      item.end = item.end.addMinutes(timezoneoffset).format("YYYY-MM-DD HH:mm");
    if (!item.split) item.split = "?";
    return item;
  });
};

const eventHappend = (e: any) => {
  console.log("eventHappend", e);
  // alert("event happend")
};
const viewChange = (e: any) => {
  selectedDate.value = e.startDate;
  emits("viewChange", e);
};
const allresources = computed(() => {
  const tmplist = props.resources.map((r) => {
    if (!r.id) r.id = r._id;
    if (r.hide === undefined) r.hide = false;
    if (!r.displayName) r.displayName = r.label;
    return r;
  });
  tmplist.push({
    _id: "?",
    id: "?",
    hide: false,
    label: t("unknown"),
    displayName: t("unknown"),
    code: "",
    email: "",
  });
  return tmplist;
});
const onCellClick = async (e: CalViewClickSlotEvent) => {
  const date = e.date;
  date.setHours(date.getHours() + Math.floor(date.getMinutes() / 60));
  date.setMinutes(0, 0, 0); // Resets also seconds and milliseconds

  const newevent: CalEventType<T> = {
    id: randomUUID(),
    start: date.format("YYYY-MM-DD HH:mm"),
    end: date.addHours(1).format("YYYY-MM-DD HH:mm"),
    class: "nostudent",
    title: t("new"),
    // content?: string | undefined;
    split: e.split,
    data: { _id: randomUUID(), day: "tue" } as T,
  };
  // emits('slotClick',e)
  // console.log("Before add ",allEvents.value)
  allEvents.value.push(newevent);
  setTimeout(() => {
    mapEvents();
  }, 300);
  // console.log("after add ",allEvents.value)
  emits("eventDragNew", newevent);
};
const onEventDrop = async (relocateData: RelocateEvent<T>) => {
  emits("eventDrop", relocateData);
};
const clickResource = async (splitid: string, splitlabel: string) =>
  emits("resourceClick", splitid, splitlabel);
const onDragNew = (e: CalEventType<T>) => emits("eventDragNew", e);

const onRightClick = (clickevent: any, scheduledata: CalEventType<T>) => {
  selectedSchedule.value = scheduledata;
  emits("eventRightClick", clickevent, scheduledata);
};
const onEventClick = (eventdata: CalEventType<T>, e:MouseEvent) => {
  selectedSchedule.value = eventdata;
  emits("eventClick", eventdata,e);
  // e.stopPropagation();
};

const calendarMode = computed(() => {
  if (useDevice().isMobile) {
    return {
      title: false,
      drag: true,
      resize: false,
      delete: false,
      // create: true,
    };
  } else {
    return {
      title: false,
      drag: true,
      resize: false,
      delete: false,
      create: true,
    };
  }
});
onMounted(() => {
  mapEvents();
  watch(
    () => props.items,
    () => mapEvents(),
  );
});
</script>
