<template>
  <LadingPage/>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2023-09-09
 * author: Ks Tan
 */
import LadingPage from '../../tenant.vue'
</script>