<template>
  <div class="w-full flex flex-col p-3">

  
    <div><TextTitle>{{ t('user') }}</TextTitle></div>
    <div class="flex flex-row w-full ">
      <title>{{ t("user") }}</title>    
      
      <div class="w-full md:w-1/2 xl:w-1/3">
        <TabView>
          <TabPanel header="Active">
            <ul role="list" class="divide-y divide-gray-100">
              <li v-for="item in userlist" :key="item.email">
                <NuxtLink
                  v-if="item.uid && item.active"
                  :to="getDocumentUrl('user', item._id)"
                >
                  <UserProfileListItem :data="item"></UserProfileListItem>
                </NuxtLink>
              </li>
            </ul>
          </TabPanel>
          <TabPanel header="Inactive">
            <ul role="list" class="divide-y divide-gray-100">
              <li v-for="item in userlist" :key="item.email">
                <NuxtLink
                  v-if="item.uid && !item.active"
                  :to="getDocumentUrl('user', item._id)"
                >
                  <UserProfileListItem :data="item"></UserProfileListItem>
                </NuxtLink>
              </li>
            </ul>
          </TabPanel>
          <TabPanel header="Invite">
            <div class="padding p-2">
              <form @submit.prevent="true" class="w-full">
                <div class="p-inputgroup flex flex-row">
                  <InputText
                    class="flex-1"
                    type="email"
                    placeholder="email"
                    v-model="inviteemail"
                  />
                  <div class="p-inputgroup-addon p p-0">
                    <button
                      label="Search"
                      class="border rounded-tl-none rounded-bl-none btn btn-primary -ml-1 h-full p-3 rounded-r-md"
                      @click="invite"
                    >
                      Invite
                    </button>
                  </div>
                </div>
              </form>
            </div>
            <ul role="list" class="divide-y divide-gray-100">
              <li v-for="item in userlist" :key="item.email">
                <NuxtLink v-if="!item.uid" :to="getDocumentUrl('user', item._id)">
                  <UserProfileListItem :data="item"></UserProfileListItem>
                </NuxtLink>
              </li>
            </ul>
          </TabPanel>
        </TabView>
      </div>
      <div v-if="!isMobile()" class="flex-1">
        <NuxtPage :_id="userid" />
      </div>
      <OverlaySideBarCrud
        v-if="dialogvisible"
        v-model="dialogvisible"
        closeEventName="user"
      >
        <NuxtPage :_id="userid" />
      </OverlaySideBarCrud>
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
// import userchild from './userchild.vue'
import Menu from "primevue/menu";
import Dialog from "primevue/dialog";
import { SearchBody, EventType, UserProfile } from "~/types";
import _ from "lodash";
import Panel from "primevue/panel";
import { ref } from "vue";
import {
  UserListItem,
  BranchListItem,
  OrgListItem,
  PermissionListItem,
} from "~/types";
import SelectButton from "primevue/selectbutton";
import Button from "primevue/button";
import InputText from "primevue/inputtext";
import Card from "primevue/card";
import TabView from "primevue/tabview";
import TabPanel from "primevue/tabpanel";
import { Permission, User } from "~/simpleapp/generate/openapi/api";
import BlockUI from "primevue/blockui";
const dialogvisible = ref(false);
//initialize api
const {
  $listen,
  $PermissionDoc,
  $OrganizationDoc,
  $BranchDoc,
  $UserDoc,
  // $InvitationDoc,
} = useNuxtApp();
const userid = computed(() => getPathPara("id"));
const permdoc = $PermissionDoc();
const orgdoc = $OrganizationDoc();
const branchdoc = $BranchDoc();
// const invitedoc = $InvitationDoc();
const userdoc = $UserDoc();
const userdata = userdoc.getReactiveData();
//initialize require list in UI
const permlist = ref<PermissionListItem[]>([]);
const userlist = ref<UserListItem[]>([]);
const orglist = ref<OrgListItem[]>([]);
const branchlist = ref<BranchListItem[]>([]);
const currentpermissions = ref<Permission[]>([]);
const grouplist = getAllGroups().map((item) => {
  return { value: item, label: _.capitalize(item) };
});

//initialize some runtime variable
const blockscreen = ref(false);
const inviteemail = ref("");
const selected = ref("");
const activeuser = ref("");
const showpermissioninfo = ref(false);
const permissionselected = ref();

const selectUser = (user: any) => {
  // goTo('user',user._id)
};

/**
 * 1. get all users from this tenant
 * @param resetpage after reload, will it reset user interface or remain as current
 */
const refreshList = async (resetpage: boolean = true) => {
  const items: any[] = [];
  const searchbody: SearchBody = {
    fields: [
      "uid",
      "email",
      "created",
      "fullName",
      "active",
      "lastActivity",
      "description",
    ],
  };
  userlist.value = await userdoc.search(searchbody);
  //listUser();
  // userlist.value = _.uniqBy(permlist.value, "uid");
  if (resetpage) {
    selected.value = "";
    activeuser.value = "";
  }
  blockscreen.value = false;
  // console.log("userlist", userlist.value);
};

/**
 * identity branch object under org
 * @param org object of org
 * @param branch object of branch
 */

/**
 * generate dialog for view each user group have what permission
 */
const previewPermission = () => {
  showpermissioninfo.value = true;
};

/***** send or remove invitation  ******/

const invite = async () => {
  // const invitedata:User = {}
  const currentuser = getUserProfile();
  const inviteuserdoc = $UserDoc();
  inviteuserdoc.setNew();
  const newuserdata = inviteuserdoc.getReactiveData();
  newuserdata.value.email = inviteemail.value;
  newuserdata.value.fullName = inviteemail.value.split("@")[0];
  newuserdata.value.active = true;
  newuserdata.value.tenantId = currentuser?.tenantId;
  newuserdata.value.orgId = currentuser?.orgId;
  newuserdata.value.branchId = currentuser?.branchId;

  const invitedata = await inviteuserdoc.create();
  inviteemail.value = "";
  await refreshList();
  // onSelectUser(invitedata);
};

const showDialogIfNeeded = () => {
  if (isMobile()) {
    if (userid.value != "") dialogvisible.value = true;
    else dialogvisible.value = false;
  }
};
watch(
  () => useRoute().path,
  () => showDialogIfNeeded(),
);
$listen("RefreshDocumentList", async () => {
  await refreshList();
});
onMounted(async () => {
  await refreshList();
  showDialogIfNeeded();
});

definePageMeta({
  menuPath: "setting/user",
});
</script>
