<template>
  <NuxtLayout :name="getLayout()">      
    <SessionBlock/>
    <OverlayHoldscreen/>
    <EventDocumentViewer></EventDocumentViewer>      
    <EventDecision/>
    <EventNotification/>
    <NuxtPage/>
  </NuxtLayout>
</template>

<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-03-17
 * Author: Ks Tan
 */

watch(()=>useRoute().params['xorg'],async (newval,oldvalue)=>{
  await reloadUserStore()  
  if(getPathPara('xorg','')!=''){
    if(!getUserProfile()?.currentGroup) goTo('pickgroup')
    setGraphqlServer()
  }  
})

const getLayout = ()=>{
  const { status } = useAuth();   
   
  if(status.value=='unauthenticated') return 'loginlayout'
  else {
    if (isMobile()) return 'mobile'
    else 'default'
  } 
}

onMounted(()=>{
  const currentgroup = useCookie('currentGroup').value
  //if no xorg, no enforce pick group
  if(getCurrentXorg()){
    if (!currentgroup)goTo('pickgroup')
    setGraphqlServer()
  }
    
})
</script>
