/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export default defineI18nConfig(() => ({
    legacy: false,
    locale: 'en',
    
  }))