/**
 * This file was automatically generated by simpleapp generator. 
 * --remove-this-line-to-prevent-override--
 * last change 2023-10-28
 * Author: Ks Tan
 */
import path from 'path'
export default defineNuxtConfig({
  colorMode: {
    classSuffix: ''

  },  
  
  runtimeConfig:{     
    public:{
      APP_URL: process.env.APP_URL,
      API_URL: process.env.API_URL,
      DEBUGDATA: process.env.DEBUGDATA,   
      PROJECT_NAME: process.env.PROJECT_NAME,     
    }
  },
  vite: {
    vue: {
        script: {
            defineModel: true,
            propsDestructure: true
        }
    }
},
app: {
  // pageTransition: {
    // name: 'slide-fade',
    // mode: 'out-in',
    // css: false,
    
  // },
  // layoutTransition: { name: 'layout', mode: 'default' }
},
tailwindcss: {
    // Options
  },
devServer: {
    host: "0.0.0.0",
},
  modules: [
    // "@hebilicious/authjs-nuxt",
    '@nuxtjs/color-mode',
    '@nuxtjs/device',
    '@nuxtjs/i18n',
    'dayjs-nuxt',
    '@sidebase/nuxt-auth',
    'nuxt-primevue',
    '@nuxtjs/apollo',
    // '@nuxtjs/pwa', //cannot turn on, will cause nuxt cant start
    // "nuxt-security",     //temporary avoid nuxt-security cause cors
    '@vueuse/nuxt',     
    '@nuxtjs/tailwindcss',
    ['@pinia/nuxt',{
      autoImports: [
        // automatically imports `defineStore`
        'defineStore', // import { defineStore } from 'pinia'
        ['defineStore', 'definePiniaStore'], // import { defineStore as definePiniaStore } from 'pinia'
      ],
    }],
  ],  
  dayjs:{
    plugins: [ 'utc', 'duration']
  },
  device: {
    refreshOnResize: true
  },
  i18n: {
    lazy: true,
    langDir: "lang/",
    strategy: "no_prefix",
    locales: [    
      {
        code: "en",
        iso: "en",
        name: "English",
        file: "en.ts",
      },
      {
        code: "cn",
        iso: "cn",
        name: "Chinese",
        file: "cn.ts",
      
      },
    ],
    defaultLocale: "en",    
  },
  apollo: {
    clients: {
      default: {
        httpEndpoint: process.env.API_URL
      }
    },
  },
  primevue: {
    
    options: {
      ripple: true,
      inputStyle: 'filled',
    
    }, 
    components: {
      include: '*',      
      // exclude: ['chart']
    }, 
    directives: {
      include: ['Ripple', 'Tooltip','Badge','FocusTrap']
    },
    cssLayerOrder: 'tailwind-base, primevue, tailwind-utilities',
    importPT: { as: 'SimpleAppPT', from:  path.resolve(__dirname,'./assets/primevue/passthrough.ts') },
    

  },
  // pinia: {

  // },
  auth: {
    globalAppMiddleware: false
  },
  // security: {
    // corsHandler:{
      //  origin: '*' //| 'null' | (string | RegExp)[] | ((origin: string) => boolean);
      // methods?: '*' | HTTPMethod[];
      // allowHeaders?: '*' | string[];
      // exposeHeaders?: '*' | string[];
      // credentials?: boolean;
      // maxAge?: string | false;
      // preflight?: {
      //     statusCode?: number;
      // };
    // },
    // headers: {      
    //   contentSecurityPolicy: {
    //     'img-src': ["'self'", 'data:', 'https://www.gravatar.com'],
    //   },
    // },
    //csrf: true,   // been force to off csrf cash it crash with nuxt-auth
  // },
  ssr: false,
  // content: [
  //     "./index.html",
  //     "./src/**/*.{vue,js,ts,jsx,tsx}",
  //     "./node_modules/primevue/**/*.{vue,js,ts,jsx,tsx}"
  // ],
  css: [ 
    'primeicons/primeicons.css',
    path.resolve(__dirname,'./assets/css/style.css'),
    path.resolve(__dirname,'./assets/css/listview.css'),
    path.resolve(__dirname,'./assets/css/calendar.css'),
    ],        
  },
  
  // devtools: { enabled: true },
  // build: {
  //               // transpile: ["primevue"]
  //       },  

)
