  
<template>

   <PageDocList :document="doc" :columns="columns" :data="docdata" :sorts="sorts">
   <template #mobileList="{index,item}">
   </template>
   <template #dataTableColumns>
                                                                                                                                                                                                                                                                                                                                                                                                                            <Column #body="{index,data}" :header="t('customerNo')">
            <RendererLink :value="data" :setting="{path:'customer'}" :fields="['customerNo']">{{ data.customerNo }}</RendererLink>
          </Column>

                                                        <Column #body="{index,data}" :header="t('customerName')">
            <RendererLink :value="data" :setting="{path:'customer'}" :fields="['customerName']">{{ data.customerName }}</RendererLink>
          </Column>

                                                          <Column #body="{index,data}" :header="t('customerStatus')">
              {{data.customerStatus}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('email')">
              {{data.email}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('tel')">
              {{data.tel}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('active')">
              {{data.active}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('description')">
              {{data.description}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('docNoFormat')">
              <RendererViewer :value="data.docNoFormat" :setting="{documentName:'docnoformat'}" :fields="['docNoFormat']">{{ data.label }}</RendererViewer>
            </Column>            
                   </template>
   <template #default><div><NuxtPage :_id="id ?? 'new'"/></div></template>    
  </PageDocList>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2023-09-09
 * author: Ks Tan
 */
import { Customer } from '~/simpleapp/generate/openapi';

  
  const {$CustomerDoc,$listen } = useNuxtApp();
  const doc = $CustomerDoc()
  const docdata = doc.getReactiveData();
  type CustomerKey = keyof Customer 

  definePageMeta({
    menuPath:'nocategory/customer'    
  });

  const columns:CustomerKey[] = [                                                                                                                                                                                                                                                                                                                        'customerNo',
                                    'customerName',
                                    'customerStatus',
                                    'email',
                                    'tel',
                                    'active',
                                    'description',
                                        ]





  const sorts:string[][] = [
            ['customerNo','asc'],
        ]

const id=computed(()=>useRoute().params.id)
</script>

  