<template>
  <div class="frontpage-container">
    <client-only>
      <title>{{ getUserProfile()?.branchName }}</title>
    </client-only>
    <h1 class="border text-3xl text-center m-20 p-20">
      {{ t("createYourContentHere") }}
    </h1>
  </div>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
useNuxtApp().$event('SetTitle',t('home'))

onMounted(()=>{
  if(!getUserStore()?.currency || !getUserStore()?.country){
    const id=getUserStore().orgRecordId
    onScreenEditDocument<Organization>('organization',id, async (actionName:FormCrudEvent,data:Organization)=>{
      
    })
  }
})
</script>
