  
<template>

   <PageDocList :document="doc" :columns="columns" :data="docdata" :sorts="sorts">
   <template #mobileList="{index,item}">
   </template>
   <template #dataTableColumns>
                                                                                                                                                                                                                                                                                                                                                                                                                              <Column #body="{index,data}" :header="t('customer')">
              <RendererViewer :value="data.customer" :setting="{documentName:'customer'}" :fields="['customer']">{{ data.label }}</RendererViewer>
            </Column>            
                                                        <Column #body="{index,data}" :header="t('invoiceNo')">
            <RendererLink :value="data" :setting="{path:'invoice'}" :fields="['invoiceNo']">{{ data.invoiceNo }}</RendererLink>
          </Column>

                                                          <Column #body="{index,data}" :header="t('invoiceDate')">
              {{data.invoiceDate}}
            </Column>          
                                                        <Column #body="{index,data}" :header="t('invoiceTitle')">
            <RendererLink :value="data" :setting="{path:'invoice'}" :fields="['invoiceTitle']">{{ data.invoiceTitle }}</RendererLink>
          </Column>

                                                          <Column #body="{index,data}" :header="t('invoiceTotal')">
              {{data.invoiceTotal}}
            </Column>          
                                                                                              <Column #body="{index,data}" :header="t('description')">
              {{data.description}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('docNoFormat')">
              <RendererViewer :value="data.docNoFormat" :setting="{documentName:'docnoformat'}" :fields="['docNoFormat']">{{ data.label }}</RendererViewer>
            </Column>            
                   </template>
   <template #default><div><NuxtPage :_id="id ?? 'new'"/></div></template>    
  </PageDocList>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2023-09-09
 * author: Ks Tan
 */
import { Invoice } from '~/simpleapp/generate/openapi';

  
  const {$InvoiceDoc,$listen } = useNuxtApp();
  const doc = $InvoiceDoc()
  const docdata = doc.getReactiveData();
  type InvoiceKey = keyof Invoice 

  definePageMeta({
    menuPath:'nocategory/invoice'    
  });

  const columns:InvoiceKey[] = [                                                                                                                                                                                                                                                                                                                                                    'invoiceNo',
                                    'invoiceDate',
                                    'invoiceTitle',
                                    'invoiceTotal',
                                                                'description',
                                        ]





  const sorts:string[][] = [
            ['invoiceNo','asc'],
        ]

const id=computed(()=>useRoute().params.id)
</script>

  