  
<template>

   <PageDocList :document="doc" :columns="columns" :data="docdata" :sorts="sorts">
   <template #mobileList="{index,item}">
   </template>
   <template #dataTableColumns>
                                                                                                                                                                                                                                                                                                                                                                                                                            <Column #body="{index,data}" :header="t('key')">
            <RendererLink :value="data" :setting="{path:'keyvaluepair'}" :fields="['key']">{{ data.key }}</RendererLink>
          </Column>

                                                          <Column #body="{index,data}" :header="t('value')">
              {{data.value}}
            </Column>          
                   </template>
   <template #default><div><NuxtPage :_id="id ?? 'new'"/></div></template>    
  </PageDocList>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2023-09-09
 * author: Ks Tan
 */
import { Keyvaluepair } from '~/simpleapp/generate/openapi';

  
  const {$KeyvaluepairDoc,$listen } = useNuxtApp();
  const doc = $KeyvaluepairDoc()
  const docdata = doc.getReactiveData();
  type KeyvaluepairKey = keyof Keyvaluepair 

  definePageMeta({
    menuPath:'nocategory/keyvaluepair'    
  });

  const columns:KeyvaluepairKey[] = [                                                                                                                                                                                                                                                                                                                        'key',
                                    'value',
            ]





  const sorts:string[][] = [
            ['key','asc'],
        ]

const id=computed(()=>useRoute().params.id)
</script>

  