<template>
    <div class="flex flex-col w-full gap-4 p-4">
      <TextTitle class="text-center">{{ t("pickGroup") }}</TextTitle>
      <div v-for="(groupName, index) in getUserProfile()?.groups" :key="index">
        <div
          class="border rounded-lg bg-primary-500 text-white p-4 text-center"
          @click="pickGroup(groupName)"
        >
          {{ t(groupName) }}
        </div>
      </div>    
    </div>
  </template>
  <script lang="ts" setup>
  /**
   * This file was automatically generated by simpleapp generator during initialization. It is changable.
   * --remove-this-line-to-prevent-override--
   * last change 2024-04-09
   * author: Ks Tan
   */
  const pickGroup = async (groupName: string) => {
      try{        
          useCookie('currentGroup').value= groupName
          localStorage.setItem('currentGroup',groupName)
          useNuxtApp().$userstore.currentGroup = groupName;
          useNuxtApp().$event("pickGroup", groupName);
          goTo("");
      }catch(e){
          alert("something wrong")
          console.error(e)
      }
    
  };
  </script>
  