  
<template>

   <PageDocList :document="doc" :columns="columns" :data="docdata" :sorts="sorts">
   <template #mobileList="{index,item}">
   </template>
   <template #dataTableColumns>
                                                                                                                                                                                                                                                                                                                                                                                                                            <Column #body="{index,data}" :header="t('productCode')">
            <RendererLink :value="data" :setting="{path:'product'}" :fields="['productCode']">{{ data.productCode }}</RendererLink>
          </Column>

                                                        <Column #body="{index,data}" :header="t('productName')">
            <RendererLink :value="data" :setting="{path:'product'}" :fields="['productName']">{{ data.productName }}</RendererLink>
          </Column>

                                                          <Column #body="{index,data}" :header="t('category')">
              <RendererViewer :value="data.category" :setting="{documentName:'category'}" :fields="['category']">{{ data.label }}</RendererViewer>
            </Column>            
                                                          <Column #body="{index,data}" :header="t('defaultPrice')">
              {{data.defaultPrice}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('active')">
              {{data.active}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('description')">
              {{data.description}}
            </Column>          
                                                       </template>
   <template #default><div><NuxtPage :_id="id ?? 'new'"/></div></template>    
  </PageDocList>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2023-09-09
 * author: Ks Tan
 */
import { Product } from '~/simpleapp/generate/openapi';

  
  const {$ProductDoc,$listen } = useNuxtApp();
  const doc = $ProductDoc()
  const docdata = doc.getReactiveData();
  type ProductKey = keyof Product 

  definePageMeta({
    menuPath:'nocategory/product'    
  });

  const columns:ProductKey[] = [                                                                                                                                                                                                                                                                                                                        'productCode',
                                    'productName',
                                                                'defaultPrice',
                                    'active',
                                    'description',
                                        ]





  const sorts:string[][] = [
            ['productCode','asc'],
        ]

const id=computed(()=>useRoute().params.id)
</script>

  