<template>
  <profile></profile>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
import profile from "../profile.vue";
definePageMeta({
  menuPath:'setting/profile'
})
</script>
