  
<template>

   <PageDocList :document="doc" :columns="columns" :data="docdata" :sorts="sorts">
   <template #mobileList="{index,item}">
   </template>
   <template #dataTableColumns>
                                                                                                                                                                                                                                                                                                                                                                                                                            <Column #body="{index,data}" :header="t('tenantName')">
            <RendererLink :value="data" :setting="{path:'tenant'}" :fields="['tenantName']">{{ data.tenantName }}</RendererLink>
          </Column>

                                                          <Column #body="{index,data}" :header="t('active')">
              {{data.active}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('description')">
              {{data.description}}
            </Column>          
                                                          <Column #body="{index,data}" :header="t('owner')">
              <RendererViewer :value="data.owner" :setting="{documentName:'user'}" :fields="['owner']">{{ data.label }}</RendererViewer>
            </Column>            
                   </template>
   <template #default><div><NuxtPage :_id="id ?? 'new'"/></div></template>    
  </PageDocList>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2023-09-09
 * author: Ks Tan
 */
import { Tenant } from '~/simpleapp/generate/openapi';

  
  const {$TenantDoc,$listen } = useNuxtApp();
  const doc = $TenantDoc()
  const docdata = doc.getReactiveData();
  type TenantKey = keyof Tenant 

  definePageMeta({
    menuPath:'nocategory/tenant'    
  });

  const columns:TenantKey[] = [                                                                                                                                                                                                                                                                                                                        'tenantName',
                                    'active',
                                    'description',
                                        ]





  const sorts:string[][] = [
            ['tenantId','asc'],
        ]

const id=computed(()=>useRoute().params.id)
</script>

  