  
<template>    
    <div>
         
            <title v-if="id">{{ data.orgName }}</title>
         
    <SimpleAppForm #default="o" :document="doc">                    
        <SimpleAppFormToolBar  :document="doc" @on="actionListener"></SimpleAppFormToolBar>        
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 p-2">
               
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                 
                                        <SimpleAppInput :input-type="SimpleAppInputType.text"  :setting="o.getField('#/properties/orgCode')" v-model="data.orgCode" />            
                  
                    
                                 
                                        <SimpleAppInput :input-type="SimpleAppInputType.text"  :setting="o.getField('#/properties/orgName')" v-model="data.orgName" />            
                  
                    
                                 
                                        <SimpleAppInput :input-type="SimpleAppInputType.text"  :setting="o.getField('#/properties/registrationNo')" v-model="data.registrationNo" />            
                  
                    
                            <SimpleAppInput :input-type="SimpleAppInputType.checkbox"  :setting="o.getField('#/properties/active')" v-model="data.active" />                    
                                 
                                    <SimpleAppInput :input-type="SimpleAppInputType.textarea"  :setting="o.getField('#/properties/description')" v-model="data.description" />            
                  
                    
                                 
                                        <SimpleAppInput :input-type="SimpleAppInputType.text"  :setting="o.getField('#/properties/timeZone')" v-model="data.timeZone" />            
                  
                    
                            <SimpleAppInput :input-type="SimpleAppInputType.number"  :setting="o.getField('#/properties/offsetMinute')" v-model="data.offsetMinute" />            
                    
                                 
                                        <SimpleAppInput :input-type="SimpleAppInputType.text"  :setting="o.getField('#/properties/currency')" v-model="data.currency" />            
                  
                    
                                 
                                        <SimpleAppInput :input-type="SimpleAppInputType.text"  :setting="o.getField('#/properties/country')" v-model="data.country" />            
                  
                
      </div>        
    </SimpleAppForm>
    <DebugDocumentData v-model="data" :label="doc.getDocName()"/>
    </div>
</template>


<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-16
 * Author: Ks Tan
 */
 import { SimpleAppInputType,FormCrudEvent } from "~/types";
 import { Organization } from "~/simpleapp/generate/types";
import { OrganizationDoc} from "~/simpleapp/docs/OrganizationDoc"


 const props = defineProps<{ _id?: string, doc?: OrganizationDoc , paras?:Organization}>();
 const doc = props.doc ??  useNuxtApp().$OrganizationDoc()
 const data = doc.getReactiveData(); 
 const emits = defineEmits(["after"]);
 const id = computed(() => props._id ?? "");

/************ start default methods ****************/

const newData = () =>  doc.setNew()

const getRecord = async () => {
  if(id.value && id.value != 'new'){
    await doc.getById(id.value)
  }else{
      newData()
    } 
}

getRecord()
watch(id,async ()=> await getRecord())
/************ end default methods ****************/


const actionListener = async (actionName: string) => {  
  emits('after',actionName,data.value)  
};

onMounted(async ()=> await actionListener(FormCrudEvent.mount))
/************ start api methods ****************/

      const runGetlogo = async () =>{

        const data = {
            id: id.value
        }
        const result = await doc.runGetlogo(
                         data
        )
        
    }
      const runUploadlogo = async () =>{

        const data = {
            id: id.value
        }
        const result = await doc.runUploadlogo(
                         data
        )
        
    }
/************ end api methods ****************/

</script>