<template>
  <div>
    <title v-if="id">{{ data.docNoFormatName ?? data.docNoFormatNo }}</title>

    <SimpleAppForm #default="o" :document="doc">
      <SimpleAppFormToolBar
        :document="doc"
        @on="actionListener"
      ></SimpleAppFormToolBar>
      <div
        class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 p-2"
      >
        <SimpleAppInput
          :input-type="SimpleAppInputType.autocomplete"
          :setting="o.getField('#/properties/branch')"
          v-model="data.branch"
        />

        <SimpleAppInput
          :input-type="SimpleAppInputType.text"
          :setting="o.getField('#/properties/docNoFormatNo')"
          v-model="data.docNoFormatNo"
        />

        <SimpleAppInput
          :input-type="SimpleAppInputType.text"
          :setting="o.getField('#/properties/docNoFormatName')"
          v-model="data.docNoFormatName"
        />

        <SimpleAppInput
          :input-type="SimpleAppInputType.checkbox"
          :setting="o.getField('#/properties/active')"
          v-model="data.active"
        />
        <SimpleAppInput
          :input-type="SimpleAppInputType.checkbox"
          :setting="o.getField('#/properties/default')"
          v-model="data.default"
        />

        <SimpleAppInput
          :readonly="!doc.isNew()"
          :input-type="SimpleAppInputType.select"
          :setting="o.getField('#/properties/docNoType')"
          :options="getAllDocFormats().map((item) => item.docType)"
          v-model="data.docNoType"
        />

        <SimpleAppInput
          :input-type="SimpleAppInputType.text"
          :setting="o.getField('#/properties/docNoPattern')"
          v-model="data.docNoPattern"
          @keyup="updateSample"
          :description="sample"
          v-tooltip="'Examples: PO-[00000], SI{YY}/[000], SI{YYMM}/[000]'"
        />

        <SimpleAppInput
          :input-type="SimpleAppInputType.number"
          :setting="o.getField('#/properties/nextNumber')"
          v-model="data.nextNumber"
        />
      </div>
    </SimpleAppForm>
    <DebugDocumentData v-model="data" :label="doc.getDocName()" />
  </div>
</template>

<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * last change 2024-02-16
 * Author: Ks Tan
 */
import { SimpleAppInputType, FormCrudEvent } from "~/types";
import { Docnoformat } from "~/simpleapp/generate/types";
import { DocnoformatDoc } from "~/simpleapp/docs/DocnoformatDoc";

const props = defineProps<{
  _id?: string;
  doc?: DocnoformatDoc;
  paras?: Docnoformat;
}>();

const doc = props.doc ?? useNuxtApp().$DocnoformatDoc();
const data = doc.getReactiveData();
const sample = ref("");
const emits = defineEmits(["after"]);
const id = computed(() => props._id ?? "");

/************ start default methods ****************/

const newData = () => doc.setNew();

const getRecord = async () => {
  if (id.value && id.value != "new") {
    await doc.getById(id.value);
  } else {
    newData();
  }
};

getRecord();
watch(id, async () => await getRecord());
/************ end default methods ****************/

const actionListener = async (actionName: string) => {
  emits("after", actionName, data.value);
};

onMounted(async () => {
  await actionListener(FormCrudEvent.mount);
  setTimeout(() => {
    updateSample();
  }, 300);
});
/************ start api methods ****************/

// const runListDocFormats = async () => {
//   const data = {
//     id: id.value,
//   };
//   const result = await doc.runListDocFormats(
//     doctype,

//     data,
//   );
// };
/************ end api methods ****************/
const updateSample = () => {
  sample.value = "Example: " + previewDocNo();
};

const previewDocNo = (): string => {
  const pattern = data.value.docNoPattern;
  if (pattern) {
    const numberReg: RegExp = /\[(.*?)\]/g;
    const dateReg: RegExp = /\{(.*?)\}/g;
    let newvalue = pattern;
    const numberpattern = pattern.match(numberReg);
    const datepattern = pattern.match(dateReg);

    if (numberpattern && numberpattern.length > 0) {
      const numberlength = numberpattern[0]
        .replace("[", "")
        .replace("]", "").length;

      let nextnumber = (data.value.nextNumber ?? 0).toString();

      const numberdiff = numberlength - nextnumber.length;

      for (let n = 0; n < numberdiff; n++) {
        nextnumber = "0" + nextnumber;
      }
      newvalue = newvalue.replace(numberpattern[0], nextnumber);
    }

    if (datepattern && datepattern.length > 0) {
      for (let d = 0; d < datepattern.length; d++) {
        const dpattern = datepattern[d];
        const date = new Date();
        const formatteddate = getDayJs()().format(
          dpattern.replace("{", "").replace("}", ""),
        );
        newvalue = newvalue.replace(dpattern, formatteddate);
      }
    }
    return newvalue;
  } else {
    return "";
  }
};
</script>
