  
<template>    
    <div>
         
            <title v-if="id">{{ t(doc.getDocName())}}</title>
         
    <SimpleAppForm #default="o" :document="doc">                    
        <SimpleAppFormToolBar  :document="doc" @on="actionListener"></SimpleAppFormToolBar>        
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 p-2">
               
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                 
                                        <SimpleAppInput :input-type="SimpleAppInputType.text"  :setting="o.getField('#/properties/collectionName')" v-model="data.collectionName" />            
                  
                    
                                 
                                        <SimpleAppInput :input-type="SimpleAppInputType.text"  :setting="o.getField('#/properties/fieldName')" v-model="data.fieldName" />            
                  
                    
                            <SimpleAppInput :input-type="SimpleAppInputType.number"  :setting="o.getField('#/properties/nextNo')" v-model="data.nextNo" />            
                
      </div>        
    </SimpleAppForm>
    <DebugDocumentData v-model="data" :label="doc.getDocName()"/>
    </div>
</template>


<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-16
 * Author: Ks Tan
 */
 import { SimpleAppInputType,FormCrudEvent } from "~/types";
 import { Autoincreament } from "~/simpleapp/generate/types";
import { AutoincreamentDoc} from "~/simpleapp/docs/AutoincreamentDoc"


 const props = defineProps<{ _id?: string, doc?: AutoincreamentDoc , paras?:Autoincreament}>();
 const doc = props.doc ??  useNuxtApp().$AutoincreamentDoc()
 const data = doc.getReactiveData(); 
 const emits = defineEmits(["after"]);
 const id = computed(() => props._id ?? "");

/************ start default methods ****************/

const newData = () =>  doc.setNew()

const getRecord = async () => {
  if(id.value && id.value != 'new'){
    await doc.getById(id.value)
  }else{
      newData()
    } 
}

getRecord()
watch(id,async ()=> await getRecord())
/************ end default methods ****************/


const actionListener = async (actionName: string) => {  
  emits('after',actionName,data.value)  
};

onMounted(async ()=> await actionListener(FormCrudEvent.mount))
/************ start api methods ****************/

      const runGenerateNextNo = async () =>{

        const data = {
            id: id.value
        }
        const result = await doc.runGenerateNextNo(
                                                                                         
                                                                              
                    collection,
                        
                                                                              
                    field,
                        
                  
                        data
        )
        
    }
/************ end api methods ****************/

</script>