<template>
  <SimpleAppForm #default="o" :document="doc">
    <SimpleAppFormToolBar
      :document="doc"
      @on="actionListener"
    ></SimpleAppFormToolBar>
    <title v-if="id">{{ data.fullName ?? data.email }}</title>
    <TabView lazy>
      <TabPanel :header="t('profile')">
        <div
          class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 p-2"
        >
          <SimpleAppInput
            :input-type="SimpleAppInputType.text"
            :setting="o.getField('#/properties/fullName')"
            v-model="data.fullName"
          />

          <SimpleAppInput
            :input-type="SimpleAppInputType.text"
            :setting="o.getField('#/properties/email')"
            v-model="data.email"
            readonly
            type="email"
          />

          <SimpleAppInput
            :input-type="SimpleAppInputType.checkbox"
            :setting="o.getField('#/properties/active')"
            v-model="data.active"
          />

          <SimpleAppInput
            :input-type="SimpleAppInputType.text"
            :setting="o.getField('#/properties/description')"
            v-model="data.description"
          />
        </div>

        <DebugDocumentData v-model="data" :label="doc.getDocName()" />
      </TabPanel>
      <TabPanel :header="t('permission')">
        <!-- <UserButtonPermissionInfo></UserButtonPermissionInfo> -->
        <form-user-permission :id="id"></form-user-permission>
      </TabPanel>
    </TabView>
  </SimpleAppForm>
</template>

<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-16
 * Author: Ks Tan
 */
import { SimpleAppInputType, FormCrudEvent } from "~/types";
import { User } from "~/simpleapp/generate/types";
import { UserDoc } from "~/simpleapp/docs/UserDoc";

const props = defineProps<{ _id?: string; doc?: UserDoc; paras?: User }>();
const doc = props.doc ?? useNuxtApp().$UserDoc();
const data = doc.getReactiveData();
const emits = defineEmits(["after"]);
const id = computed(() => props._id ?? "");

/************ start default methods ****************/

const newData = () => doc.setNew();

const getRecord = async () => {
  if (id.value && id.value != "new") {
    await doc.getById(id.value);
  } else {
    newData();
  }
};

getRecord();
watch(id, async () => await getRecord());
/************ end default methods ****************/

const actionListener = async (actionName: string) => {
  emits("after", actionName, data.value);
};

onMounted(async () => await actionListener(FormCrudEvent.mount));
/************ start api methods ****************/

/************ end api methods ****************/
</script>
