<template>
  <SimpleAppForm #default="o" :document="doc">
    <client-only>
      <title v-if="id">{{ data.branchName ?? data.branchCode }}</title>

      <SimpleAppFormToolBar
        :document="doc"
        @on="actionListener"
      ></SimpleAppFormToolBar>
      <div
        class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 p-2"
      >
        <SimpleAppInput
          :input-type="SimpleAppInputType.text"
          :setting="o.getField('#/properties/branchName')"
          v-model="data.branchName"
        />

        <SimpleAppInput
          :input-type="SimpleAppInputType.text"
          :setting="o.getField('#/properties/branchCode')"
          v-model="data.branchCode"
        />

        <SimpleAppInput
          :input-type="SimpleAppInputType.checkbox"
          :setting="o.getField('#/properties/active')"
          v-model="data.active"
        />

        <SimpleAppInput
          :input-type="SimpleAppInputType.textarea"
          :setting="o.getField('#/properties/description')"
          v-model="data.description"
        />
      </div>
    </client-only>
  </SimpleAppForm>
  <DebugDocumentData v-model="data" :label="doc.getDocName()" />
</template>

<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. 
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
import { SimpleAppInputType, FormCrudEvent } from "~/types";
import { Branch } from "~/simpleapp/generate/types";
import { BranchDoc } from "~/simpleapp/docs/BranchDoc";

const props = defineProps<{
  _id?: string;
  doc?: BranchDoc;
  paras?: Branch;
}>();
const doc = props.doc ?? useNuxtApp().$BranchDoc();
const data = doc.getReactiveData();
const emits = defineEmits(["after"]);
const id = computed(() => props._id ?? "");

/************ start default methods ****************/

const newData = () => doc.setNew();

const getRecord = async () => {
  if (id.value && id.value != "new") {
    await doc.getById(id.value);
  } else {
    newData();
  }
};

getRecord();
watch(id, async () => await getRecord());
/************ end default methods ****************/

const actionListener = async (actionName: string) => {
  emits("after", actionName, data.value, doc);
};

onMounted(async () => await actionListener(FormCrudEvent.mount));
</script>
