/* tslint:disable */
/* eslint-disable */
/**
 * prinf format microservice
 * print format microservice
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kstan@simitgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

