/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */


export type SimpleAppDocuments = {
                     
      tenant:any,
                      
      organization:any,
                      
      branch:any,
                      
      permission:any,
                      
      autoincreament:any,
                      
      docnoformat:any,
                      
      systemmessage:any,
                      
      keyvaluepair:any,
                      
      account:any,
                      
      category:any,
                      
      customer:any,
                      
      invoice:any,
                      
      product:any,
                      
      student:any,
                      
      user:any,
    }

export type SimpleAppDocumentType = keyof SimpleAppDocuments


