/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export enum NotificationStatus {
    'info'='info',
    'error'='error',
    'warn'='warn',
    'success'='success',
}

export type Notification={
    documentName:string
    status:NotificationStatus    
    summary: string
    image? : string    
    message?: string
    data?:any
}