/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-04-14
 * Author: Ks Tan
 */
import {SimpleAppClient} from '~/simpleapp/generate/clients/SimpleAppClient'
import { SimpleAppDocumentType } from './documentlist';
  export type ForeignKey = {
    _id: string;
    label: string;
    code?: string
    [key:string]: any
  };
  
  export type DocumentMetaData =  {
    docName:string
    docType:string
    page: string 
    isolationType:string   
    documentDate:string
    docNumber:boolean
    docClass: SimpleAppClient<any,any>
    viewer?: Function
  }
  export type MenuData =  {
    label: string
    icon?: string
    command?:Function
    items?: MenuData[]
    isolationType?:string
    url?:string
  }
  
  export type DocNoFormat ={
    docNoFormatName: string
    docNoFormatNo:string
    docNoPattern:string
    active: boolean
    sample:string
    }
  
  
  export type RendererSetting ={
    documentName:SimpleAppDocumentType,
    [key:string]:any
  }
  export type SearchBody = {
      
      filter?:object;
      
      fields?: any[];
      
      sorts?: any[];
  }