/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export enum SimpleAppInputType  {
    'text'='text',
    'textarea'='textarea',

    'date'='date',
    'time'='time',
    'calendar'='calendar',
    'datetime'='datetime',

    'autocomplete'='autocomplete',
    'autocompletemultiple'='autocompletemultiple',

    'selectmultiple'='selectmultiple',
    'listmultiple'='listmultiple',

    'radio'='radio',
    'select'='select',
    'list'='list',

    'chip'='chip', 

    'checkbox'='checkbox',
    'switch'='switch',
    
    
    'documentno'='documentno',
    'password'='password',

    'number'='number',
    'money'='money',
    'rating'='rating',
    'slider'='slider',

}


export type autocompletetype={
    _id:string
    label:string
    code:string
    [key:string]:any
}
export enum FormCrudEvent  {
    'mount'='mount',
    'exit'='exit',
    'create'='create',
    'update'='update',
    'delete'='delete',
    'setDocStatus'='setDocStatus',        
}
export type FormActions = {
    [key:string]:string[]    
}

export type FormMenu = {
    type?:string
    action?:string    
    label?: string | ((...args: any) => string) | undefined
    command? : Function
    event?:FormCrudEvent
    [key:string] : any
}
