/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export type UserListItem = {
    _id: string
    uid?:string
    fullName: string
    email: string
    group:string
    active:boolean
    orgId: number
    branchId: number
    tenantId: number
  }
  export type OrgListItem = {
    orgId: number
    _Id: string
    orgCode: string
    orgName: string
  }
  export type BranchListItem = {
    _id:string
    tenantId:number
    orgId: number
    branchId: number
    branchName: string
    branchCode: string
    group:string
    active:boolean
  }
  
  
  export type PermissionListItem = {
    branchId: number  
    email:string
    fullName:string
    group:string
    active:boolean
    orgId: number
    tenantId:number
    userId:string
    _id:string
    
  }


export type UserProfile = {
  _id : string
  sessionId : string
  tenantId : number
  orgId : number
  branchId : number
  orgRecordId: string
  branchRecordId: string
  uid : string
  email : string
  branchCode: string
  branchName: string
  orgCode: string
  orgName: string
  currency:string
  country:string
  offsetMinute:number
  timeZone:string
  fullName : string
  branches: {
    _id: string
    branch: any
    group: string
    xOrg: string
  }[]
  invites: {
    _id: string;
    email: string;
    fullName: string;
    tenantId: string;
    tenantName: string;
    created: string;
  }[]
  roles: string[]
  groups: string[]
  currentGroup:string
  time: string
  moreProps: any  
}