/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export type UserTaskType = {
  
    id: string
    taskId:  string
    elementId:  string
    name:  string
    processName:  string
    assignee:  string
    candidateUsers:  string[]
    candidateGroups:  string[]
    data: any
    vars: any
    startedAt:  string
    followUpDate:  string
    dueDate:  string
    priority:  string
    type:  string
    userId: string 
}