/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
import { usePassThrough } from "primevue/passthrough";
import Tailwind from "primevue/passthrough/tailwind";

const CustomTailwind = usePassThrough(
    Tailwind,
    {        
        avatar:{
            root:{ class:'h-full w-full'},
        },
        toast:{
            root:{ class:'w-full md:w-1/2 lg:w-1/3 ml-4' , style:'position: fixed; top: 0px; right: 0px; z-index: 1102;'},
            // message:{},
            // container:{class:'w-full ' },
            // content:{class:'flex flex-row-reverse w-full'},
            // buttonContainer:{class:'hidden'},
        },
        card:{
            root:{class:'bg-white dark:bg-gray-800  shadow p-2 rounded-2xl'},
            // title:{class:''},
            // header:{class:''}
        },       
        // tabview:{
            // tabpanel:{
            //     headeraction:{class:'p-tabview-nav-link p-tabview-header-action items-center cursor-pointer flex overflow-hidden relative select-none text-decoration-none select-none border-b-2 p-5 font-bold rounded-t-md transition-shadow duration-200 m-0 transition-colors duration-200  bg-white border-blue-500 text-blue-500 dark:bg-gray-600 dark:border-blue-300 dark:text-blue-300'}
            // },
        // },
        
        // tabpanel:{
        //     headerTitle:{class:'m-0 p-0'},            
        // },
        accordiontab:{
            content:{style:'padding: 0.7rem;'}
            
        },
        selectbutton:{
            root:{class:'flex flex-row gap-1 '},
            button: ({ context }) => ({
                class: ` focus:outline-none whitespace-nowrap transition duration-150 ease-in-out rounded p-2 m-1 border dark:border-gray-600   ${context.active ? 'bg-primary-600 border-primary-400 text-white' : ''}`
            }),
            // button: ( context)  => ({
                
            //     class: ['text-center border text-gray-400 dark:border-gray-700  dark:text-gray-300 rounded-lg  p-2 cursor-pointer  hover:bg-primary-400 dark:hover:bg-primary-800 hover:text-white', context.active ? 'bg-primary-600  dark:bg-primary-700 text-white' : '']
            // }),
            label:{class: 'text-sm dark:text-white'},
        },
        //checkbox:{
        //    input:{ class:' flex items-center justify-center border-2 w-6 h-6 text-gray-600  rounded-lg transition-colors duration-200 border-gray-300 bg-white dark:border-blue-900/40 dark:bg-gray-500 hover:border-blue-500 dark:hover:border-blue-400 focus:outline-none focus:outline-offset-0 focus:shadow-[0_0_0_0.2rem_rgba(191,219,254,1)] dark:focus:shadow-[inset_0_0_0_0.2rem_rgba(147,197,253,0.5)]'}
            // p-checkbox p-component cursor-pointer inline-flex relative select-none align-bottom w-6 h-6             
        //},
        button:{root:{class: 'focus:outline-none transition duration-150 ease-in-out rounded p-2 m-1 border dark:border-gray-600'}},
        dialog:{
            root:{class:[' w-full md:w-auto bodycolorclass max-w-full md:h-3/4 lg:h-1/2 border  border-gray-400 dark:bg-gray-700 m-2 rounded-lg']},
            header:{class: 'p-dialog-header flex items-center  text-2xl justify-between shrink-0 border-t-0  rounded-tl-lg rounded-tr-lg p-6 bodycolorclass'},
            footer:{class:'p-dialog-footer flex gap-2 shrink-0 justify-end align-center border-t-0 px-6 pb-6 text-right rounded-b-lg bodycolorclass'},
            content:{class:'p-dialog-content overflow-y-auto  px-6 pb-8 pt-0  rounded-bl-lg rounded-br-lg h-full bodycolorclass'}
        },        
        calendar:{
            panel:{class:'p-datepicker p-component p-datepicker-mobile p-datepicker-touch-ui p-input-filled bg-white dark:bg-gray-900 min-w-[350px] shadow-md border-0 absolute'},
            // group:{class:'p-datepicker-group flex-1 border-l border-gray-300 pr-0.5 pl-0.5 pt-0 pb-0 first:pl-0 first:border-l-0 w-2/3'},
            // table:{class:'p-datepicker-calendar border-collapse w-2/3 my-2'},
            // day:{class:'p-datepicker-other-month p-1'},
            daylabel:{class:'w-8 h-8md:w-10  md:w-10 rounded-full transition-shadow duration-200 border-transparent border flex items-center justify-center mx-auto overflow-hidden relative focus:outline-none focus:outline-offset-0 focus:shadow-[0_0_0_0.2rem_rgba(191,219,254,1)] dark:focus:shadow-[0_0_0_0.2rem_rgba(147,197,253,0.5)] cursor-pointer text-gray-600 dark:text-gray-400 bg-transparent hover:bg-gray-200 dark:hover:bg-gray-800/80'},
        //     root:{class:'border border-grey-900 dark:!border-blue-900/40  rounded-lg flex flex-row p-0'},            
        //     input:{class:'w-full p-inputtext p-component font-sans text-base text-gray-600 dark:text-white/80 bg-white dark:bg-gray-900 p-3 border border-gray-300 dark:border-blue-900/40 transition-colors duration-200 appearance-none hover:border-blue-500 rounded-lg'},
        },
        autocomplete:{
            // root:{class:'border border-gray-400 dark:!border-blue-900/40  rounded-lg flex flex-row'},
            // loadingIcon:{class:'hidden'},
            panel:{
                class:'p-autocomplete-panel p-component p-2 w-full md:max-w-[500px] p-input-filled bg-white text-gray-700 border-0 rounded-md shadow-lg max-h-[200px] overflow-auto dark:bg-gray-900 dark:text-white/80'
            },
            dropdownbutton: {
                root:' btn-primary dark:shadow-primary-800 dark:border-primary-900 text-white rounded-lg flex flex-row  p-3 rounded-tl-none rounded-bl-none '
            }
        },
        column:{
            bodycell:{
                style:'padding:5px;'
            },
        },
        sidebar:{
            root:{class:'w-full md:w-2/3  bodycolorclass  p-0 h-full'},
            header:{class:'dark:text-white text-2xl p-2'},
            content:{class:'p-0 pt-0 h-full w-full grow overflow-y-auto'}
        },        
        // panel: {
            // root:{class:['p-0']},
        //     title: {class: ['leading-none font-light text-2xl']},
            // header:{style:'padding: 0.7rem;'},
        //     content:{class:[' dark:bg-gray-600']}
        // },
        breadcrumb:{
            root:{class:''}
        },
        // inputnumber:{            
            // input:{class:'text-right text-yellow-700'}
        // }
    },
);



export default CustomTailwind;