/**
 * This file was automatically generated by simpleapp generator.
 * you may change it, it won't override
 * last change 2023-09-24
 * Author: Ks Tan
 */

import  {BranchClient} from "../generate/clients/BranchClient"
export class BranchDoc extends BranchClient{

}
