/**
 * This file was automatically generated by simpleapp generator.
 * you may change it, it won't override
 * last change 2023-09-24
 * Author: Ks Tan
 */

import  {InvoiceClient} from "../generate/clients/InvoiceClient"
export class InvoiceDoc extends InvoiceClient{

}
