/**
 * This file was automatically generated by simpleapp generator.
 * you may change it, it won't override
 * last change 2023-09-24
 * Author: Ks Tan
 */

import  {UserClient} from "../generate/clients/UserClient"
export class UserDoc extends UserClient{

}
