<template>
  <LazyFormBranch :_id="_id" @after="after" />
</template>

<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * last change 2023-09-09
 * author: Ks Tan
 */

import { Branch } from "~/simpleapp/generate/types";
const doc = useNuxtApp().$BranchDoc();

const props = defineProps<{ _id: string }>();
const after = (actionName: string, data: Branch) => {
  console.log("Branch capture after emits ", actionName,doc.getDocName().toLowerCase());
  switch (actionName) {
    case "new":
      goTo('organization');
      break;
    case "create":
      goTo('organization');
      refreshDocumentList('branch');
      useNuxtApp().$event("CloseDialog", doc.getDocName().toLowerCase());
      break;
    case "update":
      goTo('organization');
      refreshDocumentList('branch');
      useNuxtApp().$event("CloseDialog", doc.getDocName().toLowerCase());      
      break;
    case "delete":
      goTo('organization');
      refreshDocumentList('branch');
      useNuxtApp().$event("CloseDialog", doc.getDocName().toLowerCase());
      break;
  }
};
</script>
