<template>
  <LazyFormBranch _id="new" @after="after" />
</template>

<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * last change 2023-09-09
 * author: Ks Tan
 */

import { Branch } from "~/simpleapp/generate/types";
const doc = useNuxtApp().$BranchDoc();


const after = (actionName: string, data: Branch) => {
  console.log("Branch capture after emits ", actionName,'branch');
  switch (actionName) {
    case "create":
      goTo('organization');
      refreshDocumentList('branch');
      useNuxtApp().$event("CloseDialog", 'branch');
      break;
    case "update":
      goTo('organization');
      refreshDocumentList('branch');
      useNuxtApp().$event("CloseDialog", 'branch');
      

      break;
    case "delete":
      goTo('organization');
      refreshDocumentList('branch');
      useNuxtApp().$event("CloseDialog", 'branch');
      break;
  }
};
</script>
