<template>
    <LazyFormSystemmessage :_id="_id" @after="after" :paras="paras"/>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp everytime regenerate code.
 * --remove-this-line-to-prevent-override--
 * last change 2023-09-09
 * author: Ks Tan
 */
import {Systemmessage} from '~/simpleapp/generate/types'
const props = defineProps<{_id:string,paras?:Systemmessage}>();
const emits = defineEmits(["afterCreate","after"]);

const after = (actionName: string, data: Systemmessage) => {
  switch (actionName) {
    case "new":
      break;
    case "create":
      emits("afterCreate", data);
      break;
    case "update":
      break;
    case "delete":
      break;
  }
  emits("after",actionName,data)
};
</script>