<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2024-03-05
 * author: Ks Tan
 */
const alltenants = ref<any[]>([])
const totaltenant = ref(0)
  const list = (await getPorfileApi().getAllTenants()).data as any[];
  if(list.length==0 || list.length>1) navigateTo('/picktenant')
  else navigateTo (`/${list[0].permissions[0].xOrg}`)
  
</script>
<template>
  <div>
    redirecting...
  </div>
</template>
