<template>
  <div class="p-10 m-10 text-3xl border text-center dark:text-white">
    {{ t('redirectToLoginPage') }}
    <!-- <NuxtPage /> -->
  </div>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */

definePageMeta({
  name: "Login",
  auth: false,
  layout: false
});

const route = useRoute();
const { signIn } = useAuth();
const callbackUrl = ref("");
onMounted(async () => {
  if (route.query.callbackUrl) {
    callbackUrl.value = <string>route.query.callbackUrl;
  } else {
    callbackUrl.value = "/";
  }
  callbackUrl.value = decodeURIComponent(callbackUrl.value);
  // console.log("callbackUrlcallbackUrlcallbackUrl", callbackUrl.value);
  await signIn("keycloak", { callbackUrl: callbackUrl.value });
});
</script>
