<template>
  <div class="flex flex-col w-full">
    <TextTitle class="text-center p-2">{{ t("pickYourDatabase") }}</TextTitle>
    <div class="flex flex-col">
      
      <div class="p-4">
        {{ t('welcome ') }} {{ getUserProfile()?.fullName }}
        <UserButtonCreateTenant></UserButtonCreateTenant>
      </div>
      <UserTenantPicker></UserTenantPicker>
    </div>
  </div>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2023-04-17
 * author: Ks Tan
 */
</script>
