/**
 * This file was automatically generated by simpleapp generator. It is changable
 * --remove-this-line-to-prevent-override--
 * last change 2024-04-19
 * Author: Ks Tan
 */
import { Injectable, InternalServerErrorException } from '@nestjs/common';
import { UserContext } from 'src/simpleapp/generate/commons/user.context';

@Injectable()
export class CloudApiService {
  constructor() {}


}
