/**
 * This file was automatically generated by simpleapp generator. It is changable
 * --remove-this-line-to-prevent-override--
 * last change 2024-04-19
 * Author: Ks Tan
 */
import { Module } from '@nestjs/common';
import { CloudApiService } from './cloudapi.service';
@Module({
  imports: [],
  controllers: [],
  providers: [CloudApiService],
  exports: [CloudApiService],
})
export class CloudapiModule {}
