<template>
  <div class="flex-col border-b border-gray-200 dark:border-gray-700 p-1">
    <label class="dark:text-gray-400">
      <slot name="label">
        {{ label }}
      </slot>
    </label>
    <div class="dark:text-white text-right">
      <slot name="default">{{ value }}</slot>
    </div>
  </div>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-04-24
 * Author: Ks Tan
 */
const props = defineProps<{
  label?: string;
  value?: string;
}>();
</script>
