<template>
  <div class="flex flex-col">
    <div class="flex flex-row gap-2">
      
        <TextTitle v-if="title" class="flex-1">{{ title }}</TextTitle>
      
        <div class="flex flex-row"><slot name="buttons"></slot></div>
      
        <div>
          <ButtonDefault v-if="!readOnly" @click="addRow">
            <i class="pi pi-plus"></i>
          </ButtonDefault>
        </div>
    </div>
    <ListView
      class="p-2 dark:bg-slate-900 bg-slate-200 rounded-lg"
      :list="list"
      #default="{ index, item }"
      @click="showRow"
    >
      <slot name="listbody" :item="item" :index="index">
        <div class="flex flex-row">item {{ item._id }}</div>
      </slot>
    </ListView>

    <Dialog v-model:visible="showDialog" modal :header="t('editDetails')">
      <div class="flex flex-col p-2 gap-4">
        <slot name="popupbody" :index="rowIndex" :item="list[rowIndex]">
          row {{ rowIndex }} define SimpleAppInputs here
        </slot>
      </div>
      <template #footer>
        <div v-if="!readOnly" class="flex flex-row gap-2 w-full">
          <ButtonDanger @click="deleteItem">{{ t("delete") }}</ButtonDanger>
          <ButtonPrimary @click="updateItem">{{ t("ok") }}</ButtonPrimary>
        </div>
      </template>
    </Dialog>
  </div>
</template>
<script setup lang="ts" generic="T extends { [key: string]: any }">
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-03-01
 * Author: Ks Tan
 */
const showDialog = ref(false);
const rowIndex = ref(0);
const emits = defineEmits(["addrow", "deleteitem", "itemupdated"]);
const props = defineProps<{ list: T[]; title?: string; readOnly?: boolean }>();

const showRow = (index: number, item: T) => {
  showDialog.value = true;
  rowIndex.value = index;
};
const deleteItem = () => {
  showDialog.value = false;
  props.list.splice(rowIndex.value, 1);
  emits("deleteitem");
};
const updateItem = () => {
  showDialog.value = false;
  emits("itemupdated", rowIndex.value);
};
const addRow = (event: MouseEvent) => {
  emits("addrow", MouseEvent);
  const lineno = props.list.length - 1;
  showRow(lineno, props.list[lineno]);
};
</script>
