/**
 * This file was automatically generated by simpleapp generator. It is changable
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-23
 * Author: Ks Tan
 */

import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { UserContext } from '../generate/commons/user.context';
import { AutoincreamentProcessor } from '../generate/processors/autoinc.processor';
//import { Autoincreament,AutoincreamentHooks} from '../generate/types';
import * as types from '../generate/types';
export { Autoincreament} from '../generate/types';

@Injectable()
export class AutoincreamentService extends AutoincreamentProcessor {
     
   
      
   //protected hooks: types.AutoincreamentHooks = {}
    constructor(
        @InjectModel('Autoincreament')  mydoc: Model<types.Autoincreament>
        ){
        super(mydoc)
    }

/***************************** begin x-document-api definitions *****************************************/
/*
  async runGenerateNextNo(
    appuser: UserContext,    
                                                    
                                                  
               collection: string,
                
                                                  
               field: string,
                
            
                            
        
         ){
           return "OK"
      } 
*/

/***************************** end x-document-api definitions *****************************************/
}
