/**
 * This file was automatically generated by simpleapp generator. It is changable
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-23
 * Author: Ks Tan
 */

import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { UserContext } from '../generate/commons/user.context';
import { BranchProcessor } from '../generate/processors/branch.processor';
//import { Branch,BranchHooks} from '../generate/types';
import * as types from '../generate/types';
export { Branch} from '../generate/types';

@Injectable()
export class BranchService extends BranchProcessor {
     
   
      
   //protected hooks: types.BranchHooks = {}
    constructor(
        @InjectModel('Branch')  mydoc: Model<types.Branch>
        ){
        super(mydoc)
    }

/***************************** begin x-document-api definitions *****************************************/
/*
*/

/***************************** end x-document-api definitions *****************************************/
}
