/**
 * This file was automatically generated by simpleapp generator. It is changable
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-23
 * Author: Ks Tan
 */

import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { UserContext } from '../generate/commons/user.context';
import { DocnoformatProcessor } from '../generate/processors/docno.processor';
//import { Docnoformat,DocnoformatHooks} from '../generate/types';
import * as types from '../generate/types';
export { Docnoformat} from '../generate/types';

@Injectable()
export class DocnoformatService extends DocnoformatProcessor {
     
   
      
   //protected hooks: types.DocnoformatHooks = {}
    constructor(
        @InjectModel('Docnoformat')  mydoc: Model<types.Docnoformat>
        ){
        super(mydoc)
    }

/***************************** begin x-document-api definitions *****************************************/
/*
  async runListDocFormats(
    appuser: UserContext,    
                                                    
                                      
                                                  
               doctype: string,
                
            
                            
        
         ){
           return "OK"
      } 
*/

/***************************** end x-document-api definitions *****************************************/
}
