/**
 * This file was automatically generated by simpleapp generator. It is changable
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-23
 * Author: Ks Tan
 */

import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { UserContext } from '../generate/commons/user.context';
import { OrganizationProcessor } from '../generate/processors/org.processor';
//import { Organization,OrganizationHooks} from '../generate/types';
import * as types from '../generate/types';
export { Organization} from '../generate/types';

@Injectable()
export class OrganizationService extends OrganizationProcessor {
     
   
      
   //protected hooks: types.OrganizationHooks = {}
    constructor(
        @InjectModel('Organization')  mydoc: Model<types.Organization>
        ){
        super(mydoc)
    }

/***************************** begin x-document-api definitions *****************************************/
/*
  async runGetlogo(
    appuser: UserContext,    
                        
        
         ){
           return "OK"
      } 
  async runUploadlogo(
    appuser: UserContext,    
                        
         
              data:schemas.KeyValue,
            
         ){
           return "OK"
      } 
*/

/***************************** end x-document-api definitions *****************************************/
}
