/**
 * This file was automatically generated by simpleapp generator. It is changable
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-23
 * Author: Ks Tan
 */

import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { UserContext } from '../generate/commons/user.context';
import { PermissionProcessor } from '../generate/processors/perm.processor';
//import { Permission,PermissionHooks} from '../generate/types';
import * as types from '../generate/types';
export { Permission} from '../generate/types';

@Injectable()
export class PermissionService extends PermissionProcessor {
     
   
      
   //protected hooks: types.PermissionHooks = {}
    constructor(
        @InjectModel('Permission')  mydoc: Model<types.Permission>
        ){
        super(mydoc)
    }

/***************************** begin x-document-api definitions *****************************************/
/*
*/

/***************************** end x-document-api definitions *****************************************/
}
