/**
 * This file was automatically generated by simpleapp generator. It is changable
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-23
 * Author: Ks Tan
 */

import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { UserContext } from '../generate/commons/user.context';
import { SystemmessageProcessor } from '../generate/processors/sysmsg.processor';
//import { Systemmessage,SystemmessageHooks} from '../generate/types';
import * as types from '../generate/types';
export { Systemmessage} from '../generate/types';

@Injectable()
export class SystemmessageService extends SystemmessageProcessor {
     
   
      
   //protected hooks: types.SystemmessageHooks = {}
    constructor(
        @InjectModel('Systemmessage')  mydoc: Model<types.Systemmessage>
        ){
        super(mydoc)
    }

/***************************** begin x-document-api definitions *****************************************/
/*
  async runReadmsg(
    appuser: UserContext,    
                                                                
               id: string,
                
                                      
            
                            
        
         ){
           return "OK"
      } 
*/

/***************************** end x-document-api definitions *****************************************/
}
