/**
 * This file was automatically generated by simpleapp generator.
 * DONT CHANGE THIS FILE !!
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-03-19
 * Author: Ks Tan
 */
import { Inject, Injectable, Logger } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { UserContext } from 'src/simpleapp/generate/commons/user.context';
import { User } from 'src/simpleapp/services/user.service';
import { Permission } from 'src/simpleapp/services/perm.service';
import { SimpleAppRobotUserService } from 'src/simpleapp/generate/commons/robotuser.service';

@Injectable()
export class SimpleAppListenerService {
  private systemAccessToken: string;
  private expired: string;
  logger = new Logger();
  @InjectModel('User') private readonly usermodel: Model<User>;
  @InjectModel('Permission') private readonly permmodel: Model<Permission>;
  @Inject(SimpleAppRobotUserService)
  private robotuser:SimpleAppRobotUserService;

  constructor() {}

  prepareAppUser(data: any) {
    return this.robotuser.prepareAppUser(data)
  }
}
