/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
import RendererBoolean from './RendererBoolean.vue'
import RendererDate from './RendererDate.vue'
import RendererForeignKey from './RendererForeignKey.vue'
import RendererMoney from './RendererMoney.vue'
import RendererMultiText from './RendererMultiText.vue'
import RendererViewer from './RendererViewer.vue'
import RendererLink from './RendererLink.vue'

export default {
    
      RendererBoolean,RendererDate,RendererForeignKey,RendererMoney,RendererMultiText,RendererViewer,
      RendererLink
    
  };