<template>
  <span
    v-if="setting?.collection"
    @click="viewRecord"
    class="text-primary-700 hover:text-primary-500 dark:text-primary-400 cursor-pointer"
  >
    <slot>
      {{ displayText }}
    </slot>
  </span>
  <span v-else>{{ displayText }}</span>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization.
 * DONT CHANGE THIS FILE CAUSE IT OVERRIDE
 * last change 2024-04-14
 * author: Ks Tan
 */
import { ForeignKey, FormCrudEvent, SimpleAppDocumentType } from "~/types";

type SettingProp = { collection: SimpleAppDocumentType; displayField?: string };
const modelValue = defineModel<ForeignKey>();
const emits = defineEmits(["after"]);
const props = defineProps<{ setting: SettingProp }>();
const displayText = computed(() => {
  const s = props.setting;
  if (!modelValue.value) return undefined;
  else if (!s.collection) return modelValue.value;
  else if (s.displayField) return modelValue.value[s.displayField];
  else return modelValue.value.label;
});
const { $event } = useNuxtApp();
const viewer = ref();
const viewRecord = () => {
  viewer.value = getDocument(props.setting.collection)?.viewer;

  // getDocumentUrl(setting.collection,modelValue ? modelValue['_id']:'')
  //getDocumentUrl(setting.collection,modelValue ? modelValue['_id']:'')
  $event("ViewRecord", {
    _id: modelValue.value?._id as string,
    label: modelValue.value?.label as string,
    eventId: randomUUID(),
    documentName: props.setting.collection,
    viewer: viewer.value,
    readonly: true,
    after: async (actionName: FormCrudEvent, data) => {
      emits("after", actionName, data);
    },
  });
};
</script>
