<template>
  <span v-if="modelValue">{{ toUTCDateTime(modelValue) }}</span>
  <span v-else>-</span>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator during initialization.
 * DONT CHANGE THIS FILE CAUSE IT OVERRIDE
 * last change 2024-03-10
 * author: Ks Tan
 */
const modelValue = defineModel<Date | string>();
</script>
