
<template>
    <p v-for="(f,index) in fields" >
        <span v-if="index==0">{{ value[f] }}</span>
        <span v-else class="text-gray-400 text-sm">{{ value[f] }}</span>
    </p>
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator during initialization.
 * DONT CHANGE THIS FILE CAUSE IT OVERRIDE
 * last change 2024-02-04
 * author: Ks Tan
 */
const props = defineProps(['value','fields'])

</script>