<template>
  <a @click="go" class="text-primary-700 dark:text-primary-300 dark:hover:text-primary-200 hover:text-primary-500 cursor-pointer">
    <slot name="default">
      <div>{{ value[fields[0]] }}</div>
    </slot>
  </a>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization.
 * DONT CHANGE THIS FILE CAUSE IT OVERRIDE
 * last change 2024-02-04
 * author: Ks Tan
 */

const props = defineProps<{
  fields: any;
  setting: any;
  value: any;
}>();

const go = () => {
  goTo(props.setting.path, props.value._id);  
};
</script>