<template>
  <span class="pi pi-check-circle text-green-500" v-if="modelValue">    
  </span>
  <span class="pi pi-times-circle text-red-500" v-else>  
  </span>
  
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator during initialization.
 * DONT CHANGE THIS FILE CAUSE IT OVERRIDE
 * last change 2024-02-04
 * author: Ks Tan
 */
const modelValue = defineModel<boolean>();
</script>
