<template>
  <span v-if="typeof modelValue == 'undefined' || typeof modelValue == 'string'"
    >-</span
  >
  <span v-else-if="showCurrency"> {{ currenyValue }}</span>
  <span v-else>
    {{ modelValue.toLocaleString(useI18n().defaultLocale, options) }}</span
  >
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator during initialization.
 * DONT CHANGE THIS FILE CAUSE IT OVERRIDE
 * last change 2024-02-04
 * author: Ks Tan
 */
const currenyValue = computed(() => {
  if (modelValue.value === undefined) return "-";
  return Intl.NumberFormat(useI18n().defaultLocale, {
    // style: "currency",
    // currency: getUserProfile()?.currency ?? '',
    // currencyDisplay: "symbol",
  }).format(modelValue.value);
});
const options = {
  style: "decimal", // Other options: 'currency', 'percent', etc.
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
};
const modelValue = defineModel<number>({ required: true });
const props = defineProps<{ showCurrency?: boolean }>();

</script>
