<template >
    <div class="rounded-lg  h-20 p-2" @click="showCartDialog">
        <div class="line-clamp-1 text-sm md:text-base">{{ title }}</div>
        <div class="text text-2xl md:text-3xl text-right">
            <slot name="default"></slot>
        </div>
        <Dialog  v-model:visible="dialogVisiable" modal :header="title">
            <slot name="dialogbody">
                define {{title}} body
            </slot>
        </Dialog>
    </div>
    
</template>
<script lang="ts" setup>
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-03-02
 * author: Ks Tan
 */

const props = defineProps<{
    title:string,
    showDialog?:boolean
    }>()
const dialogVisiable = ref(false)
const showCartDialog = () =>{
    console.log("showCartDialogshowCartDialog")
    if(props.showDialog) dialogVisiable.value=true
}
</script>