<template>
  <PageDocList
    :document="doc"
    :columns="columns"
    :data="docdata"
    :sorts="sorts"
  >
    <template #mobileList="{ item }">
      <!-- <div class="flex flex-row justify justify-end"> -->
        <div class="flex flex-col flex-1">
          <text-primary>{{ item.docNoFormatName }}</text-primary>
          <div class="flex flex-row gap-2">
            <text-subtitle>{{ item.docNoPattern }}</text-subtitle>
            <renderer-boolean v-model="item.active"/>
          
          </div>
        </div>
        <div class="flex flex-col text-right">
          <text-subtitle>{{ item.docNoType }}</text-subtitle>
          <text-subtitle>{{ item.nextNumber }}</text-subtitle>          
          
        </div>
      <!-- </div> -->
    </template>
    <template #dataTableColumns>
    </template>
    <template #default
      ><div><NuxtPage :_id="id ?? 'new'" /></div
    ></template>
  </PageDocList>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * last change 2023-09-09
 * author: Ks Tan
 */


const doc = useNuxtApp().$DocnoformatDoc()
const docdata = doc.getReactiveData();

definePageMeta({
  menuPath: "setting/docnoformat",
});

const columns = [
  "docNoFormatNo",
  "docNoFormatName",
  "active",
  "docNoType",
  "docNoPattern",
  "nextNumber",
];

const sorts: string[][] = [["docNoType", "asc"],["docNoFormatNo","asc"]];

const id = computed(() => useRoute().params.id);
</script>
