<template>
  <SelectTemplate 
    documentName="customer"
    @change="change"
    v-model="modelValue"    
    :placeholder="placeholder"
    :showNull="showNull"
    :allowAddNew="allowAddNew"
    :filter ="filter"
    :multiple="multiple"
    :hideLabel="hideLabel"
  />
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator.
 * --remove-this-line-to-prevent-override--
 * last change 2023-09-09
 * author: Ks Tan
 */
import { ForeignKey } from '~/types';
import { Customer } from "~/simpleapp/generate/openapi";
const emits = defineEmits(["change"]);
const modelValue = defineModel<string|string[]>();
const props = defineProps<{ 
  placeholder?: string;
  showNull?:boolean;
  allowAddNew?: boolean;
  filter?: Customer;
  multiple?:boolean;
  hideLabel?:boolean;
   }>()
const change = (id:string,data:ForeignKey) =>{
  emits('change',id,data)
}

</script>


