<template>
  <div class="w-full">
    <div v-if="waiting" class="p-4  w-full">
        waiting..
    </div>
    <div v-else  class="w-full p-4">
      
      <div v-for="tenant in alltenants" class="border rounded-lg p-2 m-2">
        <TextTitle>{{ tenant.tenantName }}</TextTitle>
        <ListView :list="tenant.permissions" url="/" idField="xOrg">
          <template #default="{item,index}">
            <div class="flex flex-row w-full justify-end">
              <TextPrimary class="flex-1">{{ item.orgName }}</TextPrimary>
              <TextPrimary>{{ item.branchCode }}</TextPrimary>
              
            </div>
          </template>
        </ListView>
      </div>
     
      <!-- <card :pt="{ header: { class: 'text-xl text-gray-600' } }">
        <template #header>
          {{ tenant.tenantName }}
        </template>
        <template #content>
          <ul>
            <li v-for="o in getOrglist(tenant)">
              <h1 class="subtitle-text">{{ o.orgName }}</h1>
              <ul
                role="list"
                class="divide-y divide-gray-100 rounded-md border border-gray-200"
              >
                <li
                  v-for="b in getBranchlist(tenant)"
                  class="w-full items-center justify-between py-4 pl-4 pr-4 text-sm route-link-list"
                >
                  <NuxtLink
                    :href="`/${b.xOrg}`"
                    v-if="o.orgId == b.orgId"
                    :external="true"
                  >
                    <div class="flex w-full flex-1 items-center">
                      <p class="flex-1 flex-shrink-0 font-bold text-primary-600">
                        {{ b.branchCode }}
                      </p>
                      <p class="text-right min-w-0 flex-1 gap-2">
                        <span href="#" class="font-medium text-gray-600">{{
                          b.group
                        }}</span>
                      </p>
                    </div>
                    <div class="flex-shrink-0">
                      <span class="font-medium text-gray-400"
                        >{{ useRuntimeConfig().public.APP_URL }}/{{
                          b.xOrg
                        }}</span
                      >
                    </div>
                  </NuxtLink>
                </li>
              </ul>
            </li>
          </ul>

        </template>
      </card> -->
    </div>
    
  </div>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
import _ from "lodash";
import TextPrimary from "../text/TextPrimary.vue";
const waiting = ref(true)
const alltenants = ref();

const loadAllTenants = async () => {
  waiting.value=false
  alltenants.value = (await getPorfileApi().getAllTenants()).data;
};

// const props = defineProps<{
//    tenant:any
// }>()
const getBranchlist = (tenant: any) => tenant.permissions;

const getOrglist = (tenant: any) =>
  _.uniqBy(getBranchlist(tenant), "orgId").map((item: any) => ({
    orgId: item.orgId,
    orgCode: item.orgCode,
    orgName: item.orgName,
  }));

onNuxtReady(() => {
  loadAllTenants();
});
</script>
