<template>
  <div>
    <div class="mt-8 md:flex justify-start md:gap-4">
      <form @submit.prevent="true" class="w-full">
        <div>{{ t("createNewCompany") }}</div>
        <div class="p-inputgroup flex flex-row">
          <InputText
            class="flex-1"
            :placeholder="t('enterYourCompanyName')"
            v-model:model-value="data.tenantName"
          />
          <div class="p-inputgroup-addon p p-0">
            <button
              :label="t('create')"
              class="border rounded-tl-none rounded-bl-none btn btn-primary -ml-1 h-full p-3 rounded-r-md"
              @click="createTenant"
              :loading="onhold"
            >
              {{ t("create") }}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-03-05
 * author: Ks Tan
 */
import { ref } from "vue";
import { AxiosResponse } from "axios";
import {EventType,NotificationStatus} from "~/types"
const visible = ref(false);
const data = ref({
  tenantName: "",
  timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  utcOffset: new Date().getTimezoneOffset()
});



const createtitle = ref("Create My Company");
const errCreateTenant = ref();
const onhold = ref(false);

const createTenant = async () => {
  onhold.value = true;

  getPorfileApi()
    .createTenant(data.value)
    .then((res: AxiosResponse) => {
      if (res && res.status && res.status == 201) {
        if (res.data && res.data["xOrg"]) {
          const xorg = res.data["xOrg"];
          navigateTo("/" + xorg, { external: true });
        }
      }
    })
    .catch((err) => {
      errCreateTenant.value = err["message"];
      console.error("errCreateTenant", err.response.data.data);

      useNuxtApp().$event('Notification',{
        documentName:'tenant',
        status: NotificationStatus.error,
        summary:t('createError'),
        data:err.response?.data?.data

      })

    })
    .finally(() => {
      onhold.value = false;
    });
};
</script>
