/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
export default {
    welcome:'欢迎',
    welcomeSimpleApp: '你好,欢迎来到 SimpleApp',
    changeHomePageMsg: '改了这面',
    category: '类别',
    /*manually fix from df.ts.eta*/
}

// or