/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-04-02
 * Author: Ks Tan
 */
import { Module } from '@nestjs/common';
import { PrintApiService } from './printapi.service';
@Module({
  imports: [],
  controllers: [],
  providers: [PrintApiService],
  exports: [PrintApiService],
})
export class PrintapiModule {}
