/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-04-02
 * Author: Ks Tan
 */

import { Injectable, InternalServerErrorException } from '@nestjs/common';
import * as api from './api';
import { UserContext } from 'src/simpleapp/generate/commons/user.context';

@Injectable()
export class PrintApiService {
  constructor() {}

  getConfig(appuser: UserContext) {
    const config: api.Configuration = {
      basePath: process.env.PRINTAPI_SERVER,
      accessToken: appuser.getUserToken(),
      isJsonMime(mime) {
        return true;
      },
    };
    return config;
  }
  async getBase64Pdf(appuser: UserContext, formatid: string, id: string) {
    const printapi = new api.DefaultApi(this.getConfig(appuser), undefined);
    try{
      const result:any = await printapi.runPdfBase64(formatid, id, {
        headers: {
          'x-org': appuser.getXorg(),
        },
      });

      const pdfresult: string = result.data;
      return pdfresult;  
    }catch(e){
      throw new InternalServerErrorException('print-service servicer error')
    }
    
  }
}
