/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { defineNuxtPlugin } from "#app";
import {PROFILEApi} from '../simpleapp/generate/openapi'
import {UserProfile} from '~/types'
import axios, { Axios, AxiosResponse } from 'axios'
import _ from 'lodash'
import { group } from "console";


export default defineNuxtPlugin( async(nuxtApp) => {
    const useUserStore = defineStore('userstore', {
        state: ()=>({      
          _id: ref(''),  
          sessionId:ref(''),
          tenantId:ref(0),
          orgId:ref(0),
          branchId:ref(0),
          branchRecordId:ref(''),
          branchCode:ref(''),
          branchName:ref(''),
          orgRecordId:ref(''),
          orgCode:ref(''),
          orgName:ref(''),
          timeZone:ref(''),
          currency:ref(''),
          country: ref(''),
          offsetMinute: ref(0),
          uid: ref(''),
          email: ref(''),
          fullName: ref(''),
          roles:ref<string[]>([]),
          groups:ref<string[]>([]),
          currentGroup:ref(''),
          branches:ref([]),
          invites : ref([]),
          time:ref(''),
          moreProps:ref()
        }),
        
        actions:{    
          async loadRemoteUserInfo(){
            // console.log('loadRemoteUserInfo')
            
            const {$axios} = useNuxtApp()
            const route = useRoute();
            let xorg = this.getCurrentXorg()            
            
            let apiurl=''
            if(xorg===undefined){
              apiurl = `${useRuntimeConfig().public.APP_URL}/api`
            }else{
              apiurl = `${useRuntimeConfig().public.APP_URL}/api/${xorg}`
            }
          
            return await new PROFILEApi(undefined,apiurl,$axios).getProfile().then((res:AxiosResponse)=>{            
              if(!res){
                return
              }
              this._id = res.data._id
              this.sessionId = res.data.sessionId
              this.tenantId = res.data.tenantId              
              this.orgId = res.data.orgId
              this.orgRecordId = res.data.orgRecordId
              this.branchId = res.data.branchId
              this.branchRecordId = res.data.branchRecordId
              this.branchCode = res.data.branchCode
              this.branchName = res.data.branchName
              this.orgCode = res.data.orgCode
              this.orgName = res.data.orgName
              this.timeZone = res.data.timeZone
              this.currency = res.data.currency
              this.country = res.data.country
              this.offsetMinute = res.data.offsetMinute
              this.uid = res.data.uid
              this.email = res.data.email
              this.fullName = res.data.fullName              
              this.branches = res.data.branches
              this.groups = res.data.groups                            
              this.roles = res.data.roles
              this.time = res.data.time              
              this.invites = res.data.invites
              this.moreProps = res.data.moreProps

              let cachegroup = useCookie('currentGroup').value  ?? ''                            
              if(!this.groups || !this.groups.includes(cachegroup)){
                cachegroup=''                
              }
              this.currentGroup = cachegroup
              useNuxtApp().$event('pickGroup',cachegroup)

              return Promise.resolve(true)
                // return true
            }).catch((err:any)=>{            
                return Promise.reject(err)
            })            
          },                  
          getCurrentXorg(){
            return  (useRoute().params.xorg) ? <String>useRoute().params.xorg : undefined           
          },
          async pingSession(){
            let xorg = this.getCurrentXorg() 
            let apiurl=''
            if(!xorg){
              apiurl = `${useRuntimeConfig().public.APP_URL}/api`
            }else{
            apiurl = `${useRuntimeConfig().public.APP_URL}/api/${xorg}`
            }
            const {$axios} = useNuxtApp()
            const pingresult = await new PROFILEApi(undefined,apiurl,$axios).getSession()
            return pingresult
          },
          async decideInvitation(id:string,decision:string){
            const apiurl = `${useRuntimeConfig().public.APP_URL}/api`
            const {$axios} = useNuxtApp()
            console.log("decideInvitation",id,decision)
            const result = await new PROFILEApi(undefined,apiurl,$axios).decideInvitation(id,decision)
            
            if(result){
              console.log(result)
            }else{
              console.log(result)
            }
            //().then((res:AxiosResponse)=>{ }
          },
          canPerform(resourcename:string,action:string):boolean{

            if(
              this.roles.includes('superadmin') ||
              this.roles.includes('tenantowner') ||
              this.roles.includes('superuser') 
              ){
              return true
            }else{
              const checkstr= `${resourcename}:${action}`
              // console.log("verify",checkstr)
              return this.roles.includes(checkstr)
            }
          },
          haveAccess(resourcename:string){          
            //super admin always full access right
            resourcename = _.upperFirst(resourcename)
            // console.log("have access",resourcename)
            if(
              this.roles.includes('superadmin') ||
              this.roles.includes('tenantowner') ||
              this.roles.includes('superuser') 
              ){
              return true
            }
            for(let i=0; i< this.roles.length; i++){
            const role:string = this.roles[i]
             if(role.includes(resourcename)){
                return true
              }
            }
            return false                        
          },
          async logout (redirecturl:string){
            const redirectdata = encodeURIComponent(redirecturl)
            const { signOut } = useAuth();    
            const { data } = await <any>useFetch('/api/auth/logout');    
            // remove session
            await signOut({redirect:false});
            let addPath = encodeURIComponent(`/login?callbackUrl=${redirectdata}`);    
            const tourl= `${data.value.path}${addPath}`            
            navigateTo(tourl,{external:true})
          },
          getUserInfo(){
            const userinfo:UserProfile = {
              _id : this._id,
              sessionId : this.sessionId,
              tenantId : this.tenantId,
              orgId : this.orgId,
              branchId : this.branchId,
              orgRecordId: this.orgRecordId,
              branchRecordId: this.branchRecordId,
              uid : this.uid,
              email : this.email,
              branchCode: this.branchCode,
              branchName: this.branchName,
              orgCode: this.orgCode,
              orgName: this.orgName,
              currency: this.currency,
              timeZone: this.timeZone,
              country: this.country,
              offsetMinute: this.offsetMinute,
              fullName : this.fullName,        
              branches:this.branches??[],
              invites: this.invites ?? [],
              roles:this.roles,
              groups:this.groups,
              currentGroup:this.currentGroup,
              time:this.time,
              moreProps: this.moreProps
              
            }
            return userinfo
          }
        }        
      })
    
    
    if( useRoute().meta.auth !==false){
      
      if(await useUserStore().pingSession()){
        await useUserStore().loadRemoteUserInfo()
        
      }else{
        await useUserStore().logout(useRoute().path)        
      }    
    }else{
      // if(await useUserStore().pingSession()){

      // }else{

      // }
    }
    
    return {

        
        provide: {
            userstore:useUserStore()
          // base64url: Base64URL
        }
    }
    
});
