/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { defineNuxtPlugin } from "#app";
import Pusher from 'pusher-js';
export default defineNuxtPlugin( async(nuxtApp) => {
    const pusherkey =  (useRuntimeConfig().app.PUSHER_KEY ?? '') as string
    const pushercluster = (useRuntimeConfig().app.PUSHER_CLUSTER ?? '') as string    
    const pusher = new Pusher(pusherkey, { cluster: pushercluster,});
    return {        
        provide: {
            pusher:pusher
        }
    }    
});
