/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { defineNuxtPlugin } from "#app";
  import {TenantDoc} from "../simpleapp/docs/TenantDoc"  
  import {OrganizationDoc} from "../simpleapp/docs/OrganizationDoc"  
  import {BranchDoc} from "../simpleapp/docs/BranchDoc"  
  import {PermissionDoc} from "../simpleapp/docs/PermissionDoc"  
  import {AutoincreamentDoc} from "../simpleapp/docs/AutoincreamentDoc"  
  import {DocnoformatDoc} from "../simpleapp/docs/DocnoformatDoc"  
  import {SystemmessageDoc} from "../simpleapp/docs/SystemmessageDoc"  
  import {KeyvaluepairDoc} from "../simpleapp/docs/KeyvaluepairDoc"  
  import {AccountDoc} from "../simpleapp/docs/AccountDoc"  
  import {CategoryDoc} from "../simpleapp/docs/CategoryDoc"  
  import {CustomerDoc} from "../simpleapp/docs/CustomerDoc"  
  import {InvoiceDoc} from "../simpleapp/docs/InvoiceDoc"  
  import {ProductDoc} from "../simpleapp/docs/ProductDoc"  
  import {StudentDoc} from "../simpleapp/docs/StudentDoc"  
  import {UserDoc} from "../simpleapp/docs/UserDoc"  

export default defineNuxtPlugin((nuxtApp) => {
    
    return {
        provide: {
                    TenantDoc:()=>new TenantDoc(),
                    OrganizationDoc:()=>new OrganizationDoc(),
                    BranchDoc:()=>new BranchDoc(),
                    PermissionDoc:()=>new PermissionDoc(),
                    AutoincreamentDoc:()=>new AutoincreamentDoc(),
                    DocnoformatDoc:()=>new DocnoformatDoc(),
                    SystemmessageDoc:()=>new SystemmessageDoc(),
                    KeyvaluepairDoc:()=>new KeyvaluepairDoc(),
                    AccountDoc:()=>new AccountDoc(),
                    CategoryDoc:()=>new CategoryDoc(),
                    CustomerDoc:()=>new CustomerDoc(),
                    InvoiceDoc:()=>new InvoiceDoc(),
                    ProductDoc:()=>new ProductDoc(),
                    StudentDoc:()=>new StudentDoc(),
                    UserDoc:()=>new UserDoc(),
                  }
    }

    //other components that you need
});
