<template>
  <div
    v-bind="$attrs"
    class="w-full bg-gray-800 dark:bg-gray-800 z-20 justify justify-between absolute h h-14 flex flex-row place-items-center opacity-90 dark:text-white text-white"
  >
    <div class="text-left "><slot name="start"></slot></div>
    <div class="flex-1 text-center line-clamp-2">
      <slot name="center"></slot>
    </div>
    <div class="text-right"><slot name="end"></slot></div>
  </div>
  <div class="h-14"></div>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
</script>
