<template>
  <Button
    v-if="isMobile()"
    @click="onActivate"
    :class="`border-none dark:text-white active:text-primary-600 click:bg-gray-600 ${animate ? 'animate-bounce' :'' }`"
  >
    <slot></slot>
  </Button>
  <Button
    v-else
    @click="onActivate"
    :class="`border-none dark:text-white active:text-primary-600 click:bg-gray-600 ${animate ? 'animate-bounce' :'' }`"
  >
    <slot></slot>
  </Button>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
const emits = defineEmits(["click"]);
const props = defineProps<{animate?:boolean}>()
let stopawhile = false;
const onActivate = (e: Event) => {
  emits("click", e);
};
</script>
