<template>
  <Button
    v-if="isMobile()"
    :class="`w-full rounded-full text-center block dark:bg-warning-600 bg-warning-600 active:bg-warning-400 text-white ${animate ? 'animate-bounce' :'' }`"
    @click="onActivate"
  >
    <slot></slot>
  </Button>
  <Button v-else :class="`btn-warn ${animate ? 'animate-bounce' :'' }`" @click="onActivate">
    <slot></slot>
  </Button>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
const emits = defineEmits(["click"]);
const props = defineProps<{animate?:boolean}>()
const onActivate = (e: Event) => {
  emits("click", e);
};
</script>
