<template>
  <div class="flex flex-row gap-2">
    <div v-for="o in options" >
      <ButtonPrimary v-if="value == o.value" @click="switchButton(o.value)">{{
        o.label
      }}</ButtonPrimary>
      <ButtonDefault v-else @click="switchButton(o.value)">{{
        o.label
      }}</ButtonDefault>
    </div>
  </div>
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
type keyvalue = { label: string; value: string };
const emits = defineEmits(["switch"]);
const props = defineProps<{
  options: keyvalue[];
  value: string;
}>();
const switchButton = (v: string) => {
  if (v != props.value) emits("switch", v);
};
</script>
