<template>
  <title v-if="!id">{{ t(doc.getDocName()) }}</title>
  <div v-if="isMobile()" class="w-full">
    <div class="p-2 flex flex-row justify-end place-items-center h-14">
      <div class="flex-1">
        <TextTitle>{{ t(doc.getDocName()) }}</TextTitle>
      </div>
      <div>
        <ButtonText
          @click="goTo(doc.getDocName(), 'new')"
          class="pi pi-plus"
        ></ButtonText>
      </div>
    </div>
    <ListDocument
      v-if="recordlist"
      @click="showDialogForm"
      :recordlist="recordlist as T[]"
      :unique-key="uniqueKey"
      :document-title="documentTitle"
    >
      <template #default="{ index, item }">
        <slot name="mobileList" :index="index" :item="item as T"></slot>
      </template>
    </ListDocument>
  </div>
  <div v-else class="simpleapp-crudsimple">
    <ListDocumentTable
      v-if="recordlist"
      :value="recordlist as T[]"
      :title="doc.getDocName()"
      :unique-key="<string>uniqueKey"
      :document-title="<string>documentTitle"
      :columns="columns"
    >
      <template #toolbar>
        <div class="w-full text-left">
          <ButtonPrimary
            class="pi pi-plus"
            @click="newData"
            v-tooltip="t('new')"
            v-if="canPerform(resourcename, 'create')"
          ></ButtonPrimary>
        </div>
      </template>
      <template #default>
        <slot name="dataTableColumns">
          <Column
            v-for="col in columns.filter((item, index) => index < 6)"
            :header="t(col)"
            class="min-w-[5rem]"
            #body="{ index, data }"
          >
            <RendererLink
              v-if="uniqueKey === col || documentTitle === col"
              :value="data"
              :setting="{ path: resourcename.toLocaleLowerCase() }"
              :fields="[col]"
            >
              {{ data[col] }}
            </RendererLink>
            <span v-else-if="data[col]?.label !== undefined">{{
              data[col].label
            }}</span>
            <span v-else>{{ data[col] }}</span>
          </Column>
        </slot>
      </template>
    </ListDocumentTable>
  </div>
  <OverlaySideBarCrud
    v-model="showDialog"
    :closeEventName="doc.getDocName()"
    #default
    ><slot name="default">
      <NuxtPage :_id="id"></NuxtPage>
    </slot>
  </OverlaySideBarCrud>
</template>

<script setup lang="ts" generic="T extends { [key: string]: any }">
/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
import { ref } from "vue";
import _ from "lodash";
import { SearchBody } from "~/types";
import { SimpleAppClient } from "~/simpleapp/generate/clients/SimpleAppClient";
const props = defineProps<{
  document: SimpleAppClient<any, any>;
  data: T;
  columns: string[];
  mobileColumns?: string[];
  sorts?: string[][];
}>();

const emits = defineEmits(["selectRow"]);
const id = computed(() => getPathPara("id"));
const resourcename = ref(_.upperFirst(props.document.getDocName()));
const visible = ref(false);
const showDialog = ref(false);
const op = ref();
const doc = props.document;
const disabled = ref(false);

const router = useRouter();
const route = useRoute();
const filters = ref();
const popuptitle = ref(t(doc.getDocName()));
const systemwindows = ref(false);
const { $event, $listen } = useNuxtApp();
const recordlist = ref<T[]>();
const uniqueKey = doc.getSchema()["x-simpleapp-config"].uniqueKey;
const documentTitle = doc.getSchema()["x-simpleapp-config"].documentTitle;

const refresh = () => {
  const searchbody: SearchBody = {
    fields: props.columns,
    sorts: props.sorts,
  };
  doc.search(searchbody).then((res: any) => {
    recordlist.value = res;
    disabled.value = false;
  });
};
const newData = () => {
  router.push({ path: getDocumentUrl(doc.getDocName(), "new") });
  popuptitle.value = t(doc.getDocName());
  doc.setNew();
  visible.value = true;
};

onMounted(() => {
  refresh();
});
$listen("RefreshDocumentList", (data) => {
  if (data.documentName == doc.getDocName()) {
    refresh();
  }
});
const showDialogForm = (item: T) => {
  goTo(doc.getDocName(), item._id);
  popuptitle.value = <string>item[documentTitle as keyof T];
};

watch(showDialog, () => {
  if (!showDialog.value) {
    goTo(props.document.getDocName());
  }
});
watch(
  () => useRoute().path,
  async () => {
    if(!isMobile()){
      if (getPathPara("id")) {
        showDialog.value = true;
      } else {
        showDialog.value = false;
      }
    }
  },
);

onMounted(() => {
  if (id.value) {
    showDialog.value = true;
  } else {
    showDialog.value = false;
  }

  useNuxtApp().$listen("CloseDialog", (documentName: string) => {
    if (documentName == doc.getDocName()) {
      goTo(resourcename.value);
      showDialog.value = false;
    }
  });
});
</script>
