<template>
  <OverlayViewer v-model="visible">
    <!-- <template #header>
      
    </template> -->
    <div class="w-full h-full">
      <!-- <div class="flex flex-row gap-4" v-if="allview.length>0">
            <Chip              
              v-for="(v, k) in allview"
              :label="v.label"
              @remove="deleteTab"
              :removable="true"
            />
          </div> -->

      <div
        v-for="(v, k) in allview"
        v-memo="[k]"
        class="viewer-item flex flex-col"
      >
        <div>
          <component
            :is="defineAsyncComponent(v.viewer)"
            :_id="v._id"
            :readonly="v.readonly"
            :paras="v.paras"
            @after="
              (eventType: FormCrudEvent, data: any, result: any) =>
                after(v, eventType, data, result)
            "
          />
        </div>
      </div>
    </div>
  </OverlayViewer>
</template>
<script setup lang="ts">
/*
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
import { onKeyStroke } from "@vueuse/core";
import { useDialog } from "primevue/usedialog";
import { defineAsyncComponent } from "vue";
import { ViewRecord, FormCrudEvent } from "~/types";
// import TabView from 'primevue/tabview';
import Chip from "primevue/chip";

const { $listen } = useNuxtApp();
const visible = ref(false);
const allview = ref<{ [key: string]: ViewRecord }>({});
const after = (
  v: ViewRecord,
  eventType: FormCrudEvent,
  data: any,
  result: any,
) => {
  if (v.after) {
    v.after(eventType, data);
    
    //only after mount consider no remove tab
    if (eventType != "mount") deleteTab();
  }
};

onKeyStroke("Escape", (e) => {
  e.preventDefault();
  deleteTab();
});

const deleteTab = () => {
  const keys = Object.keys(allview.value);
  const lastkey = keys[keys.length - 1];
  delete allview.value[lastkey];

  // updateprops.value++
  if (Object.keys(allview.value).length == 0) {
    visible.value = false;
    useNuxtApp().$event("CloseDialog", "viewer");
    return;
  }
};

$listen("ViewRecord", (setting) => {
  visible.value = true;
  allview.value[setting.eventId] = setting;
});

$listen("CloseDialog", (documentName: string) => {
  if (!documentName) return;
  const keys = Object.keys(allview.value);
  const lastkey = keys[keys.length - 1];
  if (
    allview.value[lastkey] &&
    allview.value[lastkey].documentName == documentName
  ) {
    deleteTab();
  }
});
// $listen('C' (setting) => {
//   if(initDocumentName.value=='') initDocumentName.value= setting.documentName
//   visible.value = true;
//   allview.value[setting.eventId] = setting;
// });
</script>

<style scoped>
.viewer-item {
  display: none;
}
.viewer-item:last-child {
  display: flex;
}
</style>
