<template>
  <!-- <header>       -->
  <!-- <MegaMenu :model="getMenus()" orientation="horizontal" />               -->

  <div>
    <client-only>
      <div class="flex-1 flex flex-row gap-2 p-2">
        <!-- <div class="">
                <HeaderButtonMenuPicker/>                
            </div>      -->

        <!-- <div class="">
                <HeaderButtonHome/>                
            </div> -->
        <div
          v-if="isMobile()"
          class="dark:text-white max-w-[15rem] truncate ..."
        >
          <div v-if="useRoute().fullPath.split('/').length <= 3">
            {{ t("home") }}
          </div>
          <div v-else>{{ _.last(useRoute().fullPath.split("/")) }}</div>
        </div>
        <div v-else>
          <HeaderBreadcrumb
            class="hidden md:block"
            v-if="useRoute().fullPath != '/'"
          ></HeaderBreadcrumb>
        </div>
      </div>
     <!-- <div class="flex-1 flex flex-row-reverse gap-2 p-2">
       
            <div class=" text-right" v-if="!isMobile()">
                <HeaderButtonProfile/>
            </div>
             <div class=" text-right">
                <HeaderButtonTaskList/>
            </div> 
         <div class="">
                <HeaderSelectBranch/>              
            </div>         
      </div>-->
    </client-only>
  </div>

  <!-- </header> -->
</template>
<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-04-10
 * author: Ks Tan
 */

import _ from "lodash";
//import ButtonMenuPicker from "./ButtonMenuPicker.vue"

//import ButtonProfile from './ButtonProfile.vue';
const pageTitle = ref<string>("");
onMounted(() => {
  // useNuxtApp().$listen('SetTitle',(title:string)=>{
  // pageTitle.value = title
  // })
});
</script>
