<template>
    <div :class="`p-0 absolute bg-yellow-200 bottom-100 right-0`" v-if="isdebug=='1'">
        <button @click="visible=true"  class=" text-white text-xs bg-warning-800 p-0 m-0">
            <i class="pi pi-code"></i>{{ label }}</button>      
        <Sidebar v-model:visible="visible" class="text-red-100">
            
            <template #header >
                <h1 class="text-gray-700 text-lg font-bold content-center">{{ label }} Data</h1>    
            </template>
            <template #default>                
                <pre class="border rounder-lg m-0 p-0 dark:bg-gray-500">{{ modelValue }}
                </pre>                
            </template>
                
        </Sidebar>

    </div>
        
</template>

<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp generator during initialization. 
 * IT IS NOT CHANGABLE
 * last change 2024-02-22
 * author: Ks Tan
 */
// import Panel from 'primevue/panel';
// import ScrollPanel from 'primevue/scrollpanel';
import Dialog from 'primevue/dialog';
import Sidebar from 'primevue/sidebar';

import {ref} from 'vue'
const modelValue = defineModel()
const isdebug = ref(useRuntimeConfig().public.DEBUGDATA)
const visible = ref(false)
const props = withDefaults(defineProps<{label?:string}>(),{label:'label'})
const buttonlabel = computed(()=>props.label??'debug')
const op = ref();

</script>
