<template>
    <LazyFormBranch :_id="_id" class="w-full" @after="after" />
  </template>
  
  <script setup lang="ts">
  /**
   * This file was automatically generated by simpleapp generator.
   * --remove-this-line-to-prevent-override--
   * last change 2023-09-09
   * author: Ks Tan
   */
   
  import { Branch } from "~/simpleapp/generate/types";
  const doc = useNuxtApp().$BranchDoc();
  const _id = getPathPara("id", "");
  
  const after = (actionName: string, data: Branch) => {
    console.log("Branch capture after emits ", actionName);
    switch (actionName) {
      case "exit":
        goTo('organization');
        break;
      case "create":
        goTo(doc.getDocName(), data._id);
        refreshDocumentList('branch');
        goTo('organization');
        break;
      case "update":
        refreshDocumentList('branch');
        goTo('organization');
        break;
      case "delete":
        goTo(doc.getDocName(), "new");
        refreshDocumentList('branch');
        goTo('organization');
        break;
    }
  };
  </script>
  